# BASIC

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# 그래프 시각화 한글 처리
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

## 코드 실행 후 런타임 다시 시작 --> 해당 셀 제외하고 코드 실행

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-nanum is already the newest version (20200506-1).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import seaborn as sns
import datetime
import scipy.stats

%matplotlib inline
plt.rc('font', family='NanumBarunGothic')

In [ ]:
import pandas as pd

In [ ]:
%cd /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather

[Errno 2] No such file or directory: '/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather'
/content

In [ ]:
data = pd.read_csv(csv_file_path, usecols=columns_to_read)

# 2020 csv 생성

In [ ]:
%cd /content/drive/MyDrive/KOPIS DATA/Data
!unzip -qq "2020.zip"

/content/drive/MyDrive/KOPIS DATA/Data

In [ ]:
import os
import re

def rename_files_in_directory(directory_path):
    for filename in os.listdir(directory_path):
        if filename.endswith(".xlsx"):
            full_path = os.path.join(directory_path, filename)

            # "2020" 이전의 부분을 추출합니다.
            parts = filename.split("2020", 1)  # "2020"을 기준으로 1번만 split합니다.
            if len(parts) == 2:  # "2020"이 파일명에 포함되어 있어야 합니다.
                new_filename = "2020" + parts[1].strip()

                # 새로운 파일명으로 변경합니다.
                new_full_path = os.path.join(directory_path, new_filename)
                os.rename(full_path, new_full_path)
                print(f"Renamed: {filename} -> {new_filename}")

# 디렉토리 경로를 지정합니다.
directory_path = "/content/drive/MyDrive/KOPIS DATA/Data/csv/2020"
rename_files_in_directory(directory_path)

Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_01_01_10_897,439.xlsx -> _01_01_10_897,439.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_01_11_15_537,928.xlsx -> _01_11_15_537,928.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_01_16_20_663,948.xlsx -> _01_16_20_663,948.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_01_21_31_758,120.xlsx -> _01_21_31_758,120.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_02_01_10_746,735.xlsx -> _02_01_10_746,735.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_02_11_20_594,532.xlsx -> _02_11_20_594,532.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_02_21_29_442,083.xlsx -> _02_21_29_442,083.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_03_01_31_615,924.xlsx -> _03_01_31_615,924.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_04_01_30_362,518.xlsx -> _04_01_30_362,518.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_05_01_31_759,808.xlsx -> _05_01_31_759,808.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_06_01_30_682,044.xlsx -> _06_01_30_682,044.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_07_01_15_433,289.xlsx -> _07_01_15_433,289.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_07_16_31_586,525.xlsx -> _07_16_31_586,525.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_08_01_15_781,300.xlsx -> _08_01_15_781,300.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_08_16_31_663,818.xlsx -> _08_16_31_663,818.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_09_01_30_710,571.xlsx -> _09_01_30_710,571.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_10_01_15_362,012.xlsx -> _10_01_15_362,012.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_10_16_31_648,952.xlsx -> _10_16_31_648,952.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_11_01_15_669,192.xlsx -> _11_01_15_669,192.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_11_16_30_835,623.xlsx -> _11_16_30_835,623.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_12_01_15_526,975.xlsx -> _12_01_15_526,975.xlsx
Renamed: (╡е└╠┼═)_19│т ╟╧╣▌▒т~ _22│т ╟╧╣▌▒т ░°╕Ё└№ raw╡е└╠┼═_2020_12_16_31_442,866.xlsx -> _12_16_31_442,866.xlsx

In [ ]:
import os
# 주어진 디렉토리에 있는 항목들의 이름을 담고 있는 리스트를 반환합니다.
# 리스트는 임의의 순서대로 나열됩니다.
file_path = '/content/drive/MyDrive/KOPIS DATA/Data/csv/2020/'
file_names = os.listdir(file_path)
file_names

['2020_12_16_31_442,866.xlsx',
 '2020_12_01_15_526,975.xlsx',
 '2020_11_16_30_835,623.xlsx',
 '2020_11_01_15_669,192.xlsx',
 '2020_10_16_31_648,952.xlsx',
 '2020_10_01_15_362,012.xlsx',
 '2020_09_01_30_710,571.xlsx',
 '2020_08_16_31_663,818.xlsx',
 '2020_08_01_15_781,300.xlsx',
 '2020_07_16_31_586,525.xlsx',
 '2020_07_01_15_433,289.xlsx',
 '2020_06_01_30_682,044.xlsx',
 '2020_05_01_31_759,808.xlsx',
 '2020_04_01_30_362,518.xlsx',
 '2020_03_01_31_615,924.xlsx',
 '2020_02_21_29_442,083.xlsx',
 '2020_02_11_20_594,532.xlsx',
 '2020_02_01_10_746,735.xlsx',
 '2020_01_21_31_758,120.xlsx',
 '2020_01_16_20_663,948.xlsx',
 '2020_01_11_15_537,928.xlsx',
 '2020_01_01_10_897,439.xlsx']

In [ ]:
file_names[4]

'2020_02_01_10_746,735.xlsx'

In [ ]:
%cd /content/drive/MyDrive/KOPIS DATA/Data/csv/2020
dfs = []
cnt = 0
for i in range(0, 4):
    df = pd.read_excel(file_names[i])
    dfs.append(df)
    cnt += len(df)
    print(file_names[i]+' finished')

# DataFrame들을 하나로 합치기
merged_df = pd.concat(dfs, ignore_index=True)

print(cnt)
print(len(merged_df))

merged_df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/2020_1.csv', index=False)
print("Excel 파일 합치기가 완료되었습니다.")

/content/drive/MyDrive/KOPIS DATA/Data/csv/2020
2020_12_16_31_442,866.xlsx finished
2020_12_01_15_526,975.xlsx finished
2020_11_16_30_835,623.xlsx finished
2020_11_01_15_669,192.xlsx finished
2474656
2474656
Excel 파일 합치기가 완료되었습니다.

In [ ]:
%cd /content/drive/MyDrive/KOPIS DATA/Data/csv/2020
dfs = []
cnt = 0
for i in range(4, 8):
    df = pd.read_excel(file_names[i])
    dfs.append(df)
    cnt += len(df)
    print(file_names[i]+' finished')

# DataFrame들을 하나로 합치기
merged_df = pd.concat(dfs, ignore_index=True)

print(cnt)
print(len(merged_df))

merged_df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/2020_2.csv', index=False)
print("Excel 파일 합치기가 완료되었습니다.")

/content/drive/MyDrive/KOPIS DATA/Data/csv/2020
2020_10_16_31_648,952.xlsx finished
2020_10_01_15_362,012.xlsx finished
2020_09_01_30_710,571.xlsx finished
2020_08_16_31_663,818.xlsx finished
2385353
2385353
Excel 파일 합치기가 완료되었습니다.

In [ ]:
%cd /content/drive/MyDrive/KOPIS DATA/Data/csv/2020
dfs = []
cnt = 0
for i in range(8, 12):
    df = pd.read_excel(file_names[i])
    dfs.append(df)
    cnt += len(df)
    print(file_names[i]+' finished')

# DataFrame들을 하나로 합치기
merged_df = pd.concat(dfs, ignore_index=True)

print(cnt)
print(len(merged_df))

merged_df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/2020_3.csv', index=False)
print("Excel 파일 합치기가 완료되었습니다.")

/content/drive/MyDrive/KOPIS DATA/Data/csv/2020
2020_08_01_15_781,300.xlsx finished
2020_07_16_31_586,525.xlsx finished
2020_07_01_15_433,289.xlsx finished
2020_06_01_30_682,044.xlsx finished
2483158
2483158
Excel 파일 합치기가 완료되었습니다.

In [ ]:
%cd /content/drive/MyDrive/KOPIS DATA/Data/csv/2020
dfs = []
cnt = 0
for i in range(12, 17):
    df = pd.read_excel(file_names[i])
    dfs.append(df)
    cnt += len(df)
    print(file_names[i]+' finished')

# DataFrame들을 하나로 합치기
merged_df = pd.concat(dfs, ignore_index=True)

print(cnt)
print(len(merged_df))

merged_df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/2020_4.csv', index=False)
print("Excel 파일 합치기가 완료되었습니다.")

/content/drive/MyDrive/KOPIS DATA/Data/csv/2020

KeyboardInterrupt: ignored

In [ ]:
%cd /content/drive/MyDrive/KOPIS DATA/Data/csv/2020
dfs = []
cnt = 0
for i in range(17, 22):
    df = pd.read_excel(file_names[i])
    dfs.append(df)
    cnt += len(df)
    print(file_names[i]+' finished')

# DataFrame들을 하나로 합치기
merged_df = pd.concat(dfs, ignore_index=True)

print(cnt)
print(len(merged_df))

merged_df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/2020_5.csv', index=False)
print("Excel 파일 합치기가 완료되었습니다.")

/content/drive/MyDrive/KOPIS DATA/Data/csv/2020
2020_02_01_10_746,735.xlsx finished
2020_01_21_31_758,120.xlsx finished
2020_01_16_20_663,948.xlsx finished
2020_01_11_15_537,928.xlsx finished
2020_01_01_10_897,439.xlsx finished
3604170
3604170
Excel 파일 합치기가 완료되었습니다.

In [ ]:
df1 = pd.read_csv('2020_1.csv')

ParserError: ignored

# 미세먼지

## 미세먼지 null 값 대체하기

In [ ]:
%cd /content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/microdust/
import pandas as pd
import math

df = pd.read_csv('micro_dust_2019_2022.csv',encoding='cp949')

# '구분'이 '평균'인 행 제거하기
df = df[df['구분'] != '평균']
df.head()

/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/microdust

                 일시   구분  미세먼지(PM10)  초미세먼지(PM2.5)
0  2022/12/31 23:00  강남구        57.0          44.0
1  2022/12/31 23:00  강동구        68.0          55.0
2  2022/12/31 23:00  강북구        59.0          42.0
3  2022/12/31 23:00  강서구        62.0          40.0
4  2022/12/31 23:00  관악구        57.0          38.0

In [ ]:
# 날짜와 구분을 기준으로 데이터프레임을 정렬
df = df.sort_values(by=['구분', '일시']).reset_index(drop=True)

# null 값을 가장 최근의 유효한 값으로 대체
for idx, row in df.iterrows():
    if pd.isnull(row['미세먼지(PM10)']):
        prev_valid = df.loc[:idx, '미세먼지(PM10)'].dropna().iloc[-1]
        next_valid = df.loc[idx:, '미세먼지(PM10)'].dropna().iloc[0]
        df.at[idx, '미세먼지(PM10)'] = (prev_valid + next_valid) / 2

    if pd.isnull(row['초미세먼지(PM2.5)']):
        prev_valid = df.loc[:idx, '초미세먼지(PM2.5)'].dropna().iloc[-1]
        next_valid = df.loc[idx:, '초미세먼지(PM2.5)'].dropna().iloc[0]
        df.at[idx, '초미세먼지(PM2.5)'] = (prev_valid + next_valid) / 2

print(df)

                      일시   구분  미세먼지(PM10)  초미세먼지(PM2.5)
0        2019/07/01 0:00  강남구        42.0          34.0
1       2019/07/01 10:00  강남구        31.0          22.0
2       2019/07/01 11:00  강남구        28.0          22.0
3       2019/07/01 12:00  강남구        31.0          23.0
4       2019/07/01 13:00  강남구        36.0          23.0
...                  ...  ...         ...           ...
767993   2022/12/31 5:00  중랑구        35.0          27.0
767994   2022/12/31 6:00  중랑구        40.0          28.0
767995   2022/12/31 7:00  중랑구        37.0          32.0
767996   2022/12/31 8:00  중랑구        37.0          32.0
767997   2022/12/31 9:00  중랑구        39.0          30.0

[767998 rows x 4 columns]

## 미세먼지등급 분류하기

In [ ]:
# 미세먼지와 초미세먼지 등급을 반환하는 함수 정의
def get_pm10_grade(value):
    if math.isnan(value):
        return None
    elif value < 30:
        return 0
    elif value < 80:
        return 1
    elif value < 150:
        return 2
    else:
        return 3

def get_pm25_grade(value):
    if math.isnan(value):
        return None
    elif value < 15:
        return 0
    elif value < 35:
        return 1
    elif value < 75:
        return 2
    else:
        return 3

# '미세먼지등급'과 '초미세먼지등급' 칼럼 추가
df['미세먼지등급'] = df['미세먼지(PM10)'].apply(get_pm10_grade)
df['초미세먼지등급'] = df['초미세먼지(PM2.5)'].apply(get_pm25_grade)

df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/microdust/micro_dust_level.csv', index=False)

## 미세먼지 데이터 병합

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/microdust/micro_dust_level.csv')
print(df.dtypes)

/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/microdust
일시               object
구분               object
미세먼지(PM10)      float64
초미세먼지(PM2.5)    float64
미세먼지등급            int64
초미세먼지등급           int64
dtype: object

In [ ]:
df['일시'] = pd.to_datetime(df['일시'])

# 변경된 DataFrame 확인
print(df.head())

                   일시   구분  미세먼지(PM10)  초미세먼지(PM2.5)  미세먼지등급  초미세먼지등급
0 2019-07-01 00:00:00  강남구        42.0          34.0       1        1
1 2019-07-01 10:00:00  강남구        31.0          22.0       1        1
2 2019-07-01 11:00:00  강남구        28.0          22.0       0        1
3 2019-07-01 12:00:00  강남구        31.0          23.0       1        1
4 2019-07-01 13:00:00  강남구        36.0          23.0       1        1

In [ ]:
# '구분' 칼럼과 '일시' 칼럼으로 정렬
df.sort_values(by=['구분', '일시'], inplace=True)

# '구분' 칼럼 이름을 '자치구'로, '일시' 칼럼 이름을 'date'로 바꾸기
df.rename(columns={'구분': '자치구', '일시': 'date'}, inplace=True)

# 'date' 칼럼에서 시간 추출하여 'hour' 칼럼 만들기
df['hour'] = df['date'].dt.hour

# 'date' 칼럼에서 시간을 제외한 날짜만 남기기
df['date'] = df['date'].dt.date

df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/microdust/micro_dust_final.csv', index=False)

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/microdust/micro_dust_final.csv')

# 'hour' 칼럼명을 'time'으로 바꾸기
df = df.rename(columns={'hour': 'time'})

# 'time' 칼럼의 형태를 'hh:mm' 형태로 바꾸기
df['time'] = pd.to_datetime(df['time'], format='%H').dt.strftime('%H:%M')

# 'hour' 칼럼을 파일의 두 번째 열로 옮기기
cols = list(df.columns)
cols.insert(1, cols.pop(cols.index('time')))
df = df[cols]

df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/microdust/final_micro_dust.csv', index=False)

In [ ]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [date, time, 자치구, 미세먼지(PM10), 초미세먼지(PM2.5), 미세먼지등급, 초미세먼지등급]
Index: []

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/microdust/final_micro_dust.csv')
df1

              date   time  자치구  미세먼지(PM10)  초미세먼지(PM2.5)  미세먼지등급  초미세먼지등급
0       2019-07-01  00:00  강남구        42.0          34.0       1        1
1       2019-07-01  01:00  강남구        48.0          39.0       1        2
2       2019-07-01  02:00  강남구        44.0          36.0       1        2
3       2019-07-01  03:00  강남구        38.0          29.0       1        1
4       2019-07-01  04:00  강남구        35.0          28.0       1        1
...            ...    ...  ...         ...           ...     ...      ...
767993  2022-12-31  19:00  중랑구        57.0          42.0       1        2
767994  2022-12-31  20:00  중랑구        54.0          39.0       1        2
767995  2022-12-31  21:00  중랑구        51.0          39.0       1        2
767996  2022-12-31  22:00  중랑구        55.0          44.0       1        2
767997  2022-12-31  23:00  중랑구        66.0          50.0       1        2

[767998 rows x 7 columns]

# 행정동 추출

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/2020/2020_2.csv')

<ipython-input-1-cf687df6ce62>:2: DtypeWarning: Columns (19,23,27,41,52,54,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/2020/2020_2.csv')

In [ ]:
import pandas as pd
import re

seoul_district_pattern = r'(?:서울특별시\s)?(\S+구)'

seoul = df[df['주소'].str.contains('서울')]
seoul['자치구'] = seoul['주소'].apply(lambda x: re.search(seoul_district_pattern, x).group(1) if re.search(seoul_district_pattern, x) else None)

<ipython-input-2-3522dcbf5eea>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul['자치구'] = seoul['주소'].apply(lambda x: re.search(seoul_district_pattern, x).group(1) if re.search(seoul_district_pattern, x) else None)

In [ ]:
def extract_first_text_inside_parentheses(input_string):
    pattern = r'\(([^)]+)'  # 정규 표현식: 첫 번째 소괄호 안의 모든 문자를 추출
    result = re.search(pattern, str(input_string))
    if result: #소괄호가 여러번 나오는 주소가 있어 가장 먼저 나오는 소괄호만 유효하도록 함
        return result.group(1)
    return None

seoul['행정동'] = seoul['주소'].apply(extract_first_text_inside_parentheses)

<ipython-input-3-851ca6093bcc>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul['행정동'] = seoul['주소'].apply(extract_first_text_inside_parentheses)

In [ ]:
seoul = seoul.sort_values(by=['자치구']) #자치구 기준으로 sort

In [ ]:
seoul['자치구 행정동'] = seoul['자치구'] + " " + seoul['행정동']
seoul['자치구 행정동'].unique()

array(['강남구 역삼동', '강남구 삼성동', '강남구 대치동', '강남구 청담동', '강남구 신사동', '강남구 논현동',
       '강남구 일원동', '강북구 번동', '광진구 광장동', '광진구 능동', '광진구 자양동', '광진구 군자동',
       '구로구 신도림동, 디큐브시티', '구로구 오류동', '구로구 구로동, 신구로자이나인스에비뉴', '구로구 구로동',
       '구로구 고척동', '금천구 독산동', '노원구 중계동', '노원구 월계동', '동대문구 청량리동', '동작구 사당동',
       '동작구 사당동, 이수자이', '마포구 서교동', '마포구 신정동', '마포구 창전동', '마포구 대흥동',
       '마포구 성산동', '마포구 주', '서대문구 신촌동', '서대문구 대현동', '서대문구 연희동', '서대문구 창천동',
       '서대문구 홍은동', '서초구 서초동', '서초구 반포동', '서초구 잠원동', '성동구 성수동1가',
       '성동구 성수동2가', '성동구 행당동, 서울숲 더샵', '성북구 돈암동', '성북구 동선동1가',
       '성북구 성북동1가', '성북구 삼선동1가', nan, '성북구 동소문동2가', '성북구 삼선동2가',
       '송파구 잠실동', '송파구 거여동', '송파구 신천동', '송파구 방이동', '양천구 목동', '양천구 신정동',
       '영등포구 여의도동', '영등포구 당산동5가', '영등포구 문래동3가', '용산구 한남동', '용산구 용산동6가',
       '용산구 이촌동', '용산구 보광동', '용산구 이태원동 34-87', '용산구 서계동', '용산구 한강로3가',
       '은평구 녹번동', '은평구 진관동', '종로구 동숭동', '종로구 혜화동', '종로구 명륜3가', '종로구 원서동',
       '종로구 명륜2가', '종로구 종로6가', '종로구 이화동', '종로구 연지동', '종로구 부암동',
       '종로구 명륜4가', '종로구 명륜1가', '종로구 세종로', '종로구 관철동', '종로구 효제동', '종로구 효자동',
       '종로구 삼청동', '종로구 종로5가', '종로구 옥인동', '종로구 연건동', '종로구 관수동', '종로구 통의동',
       '종로구 인사동', '중구 흥인동', '중구 정동', '중구 초동', '중구 필동2가', '중구 예장동',
       '중구 을지로4가', '중구 장충동2가', '중구 저동1가', '중구 명동2가', '중구 명동1가', '중구 필동3가',
       '중구 의주로2가'], dtype=object)

# 날씨

## 날씨 압축 해제

In [ ]:
#한글 포함된 제목의 파일도 깨지지 않고 압축 해제 (윈도우에서 다운받은 csv)
%cd /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather

import zipfile

source_file = '/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/영등포구3_날씨_2019_2022.zip'

with zipfile.ZipFile(source_file, 'r') as zf:
	zipinfo = zf.infolist()
	for info in zipinfo:
		info.filename = info.filename.encode('cp437').decode('euc-kr')
		zf.extract(info)

/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather

In [ ]:
import zipfile
import os

source_file = '/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/마포구3_날씨_2019_2022.zip'

with zipfile.ZipFile(source_file, 'r') as zf:
    zipinfo = zf.infolist()
    for info in zipinfo:
        # Decode the file name using 'cp437' encoding (original encoding in zip)
        file_name = info.filename.encode('cp437').decode('utf-8')

        # Check if the file is .DS_Store and skip it
        if file_name == ".DS_Store":
            continue

        # Otherwise, extract the file
        info.filename = file_name
        zf.extract(info)

print("Zip file extracted successfully without creating .DS_Store files.")

UnicodeDecodeError: ignored

## 데이터 보정

In [ ]:
import natsort
file_list = os.listdir('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/강남구2_날씨_2019_2022')
file_list = natsort.natsorted(file_list)
file_list

['개포1동_강수_201907_202006.csv',
 '개포1동_강수_202007_202106.csv',
 '개포1동_강수_202107_202206.csv',
 '개포1동_강수_202207_202212.csv',
 '개포1동_기온_201907_202006.csv',
 '개포1동_기온_202007_202106.csv',
 '개포1동_기온_202107_202206.csv',
 '개포1동_기온_202207_202212.csv',
 '개포1동_습도_201907_202006.csv',
 '개포1동_습도_202007_202106.csv',
 '개포1동_습도_202107_202206.csv',
 '개포1동_습도_202207_202212.csv',
 '개포2동_강수_201907_202006.csv',
 '개포2동_강수_202007_202106.csv',
 '개포2동_강수_202107_202206.csv',
 '개포2동_기온_201907_202006.csv',
 '개포2동_기온_202007_202106.csv',
 '개포2동_기온_202107_202206.csv',
 '개포2동_습도_201907_202006.csv',
 '개포2동_습도_202007_202106.csv',
 '개포2동_습도_202107_202206.csv',
 '개포2동_습도_202207_202212.csv',
 '개포4동_강수_201907_202006.csv',
 '개포4동_강수_202007_202106.csv',
 '개포4동_강수_202107_202206.csv',
 '개포4동_기온_201907_202006.csv',
 '개포4동_기온_202007_202106.csv',
 '개포4동_기온_202107_202206.csv',
 '개포4동_습도_201907_202006.csv',
 '개포4동_습도_202007_202106.csv',
 '개포4동_습도_202107_202206.csv',
 '논현1동_강수_201907_202006.csv',
 '논현1동_강수_202007_202106.csv',
 '논현1동_강수_202107_202206.csv',
 '논현1동_강수_202207_202212.csv',
 '논현1동_기온_201907_202006.csv',
 '논현1동_기온_202007_202106.csv',
 '논현1동_기온_202107_202206.csv',
 '논현1동_기온_202207_202212.csv',
 '논현1동_습도_201907_202006.csv',
 '논현1동_습도_202007_202106.csv',
 '논현1동_습도_202107_202206.csv',
 '논현1동_습도_202207_202212.csv',
 '논현2동_강수_201907_202006.csv',
 '논현2동_강수_202007_202106.csv',
 '논현2동_강수_202107_202206.csv',
 '논현2동_강수_202207_202212.csv',
 '논현2동_기온_201907_202006.csv',
 '논현2동_기온_202007_202106.csv',
 '논현2동_기온_202107_202206.csv',
 '논현2동_기온_202207_202212.csv',
 '논현2동_습도_201907_202006.csv',
 '논현2동_습도_202007_202106.csv',
 '논현2동_습도_202107_202206.csv',
 '논현2동_습도_202207_202212.csv']

In [ ]:
import os
import natsort

filePath = '/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/추가_날씨/'  # 폴더 주소를 입력

fileAll = os.listdir(filePath)
fileCsv = [filePath + file[:-4] for file in fileAll if file.endswith('.csv')] # csv에만 적용해라
fileCsv = natsort.natsorted(fileCsv)

for file in fileCsv:
    df = pd.read_csv(file + '.csv')
    print(file, len(df))

In [ ]:
#행의 수가 8795, 8771, 8771, 4421이 아닌 csv 보정

import os
import pandas as pd
import shutil
import natsort

def trim_csv(input_file_path, target_row_count):
    try:
        df = pd.read_csv(input_file_path)
        current_row_count = df.shape[0]

        if current_row_count != target_row_count:
            delete_from_row = target_row_count
            df = df.iloc[:delete_from_row]

            # Save the trimmed DataFrame to the new CSV file
            output_file_path = os.path.join(output_folder, os.path.basename(input_file_path))
            df.to_csv(output_file_path, index=False)

            print(f"{input_file_path} 파일을 행의 수 {target_row_count}로 수정하여 {output_file_path}에 저장했습니다.")
        else:
            # 행 수가 목표값과 일치할 경우 복사하여 저장
            output_file_path = os.path.join(output_folder, os.path.basename(input_file_path))
            shutil.copy(input_file_path, output_file_path)

            print(f"{input_file_path} 파일은 이미 목표 행의 수와 일치하여 {output_file_path}에 저장했습니다.")
    except Exception as e:
        print(f"오류 발생: {e}")

def process_csv_files(input_folder, output_folder):
    file_list = natsort.natsorted(os.listdir(input_folder))
    csv_files = [file for file in file_list if file.endswith('.csv')]

    # 새로운 디렉토리 생성
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    # 각 파일에 대해 행 수를 맞춰주는 코드 추가
    target_row_counts = [8795, 8771, 8771, 4421]
    for i, csv_file in enumerate(csv_files):
        target_row_count = target_row_counts[i % len(target_row_counts)]
        input_file_path = os.path.join(input_folder, csv_file)

        # 행 수를 맞추고, 수정된 파일을 새로운 디렉토리에 저장
        trim_csv(input_file_path, target_row_count)

if __name__ == "__main__":
    input_folder = "/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022"
    output_folder = "/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned"

    process_csv_files(input_folder, output_folder)

/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/사직동_강수_201907_202006.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/사직동_강수_201907_202006.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/사직동_강수_202007_202106.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/사직동_강수_202007_202106.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/사직동_강수_202107_202206.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/사직동_강수_202107_202206.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/사직동_강수_202207_202212.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/사직동_강수_202207_202212.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/사직동_기온_201907_202006.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/사직동_기온_201907_202006.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/사직동_기온_202007_202106.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/사직동_기온_202007_202106.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/사직동_기온_202107_202206.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/사직동_기온_202107_202206.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/사직동_기온_202207_202212.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/사직동_기온_202207_202212.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/사직동_습도_201907_202006.csv 파일을 행의 수 8795로 수정하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/사직동_습도_201907_202006.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/사직동_습도_202007_202106.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/사직동_습도_202007_202106.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/사직동_습도_202107_202206.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/사직동_습도_202107_202206.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/사직동_습도_202207_202212.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/사직동_습도_202207_202212.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/삼청동_강수_201907_202006.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/삼청동_강수_201907_202006.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/삼청동_강수_202007_202106.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/삼청동_강수_202007_202106.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/삼청동_강수_202107_202206.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/삼청동_강수_202107_202206.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/삼청동_강수_202207_202212.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/삼청동_강수_202207_202212.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/삼청동_기온_201907_202006.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/삼청동_기온_201907_202006.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/삼청동_기온_202007_202106.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/삼청동_기온_202007_202106.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/삼청동_기온_202107_202206.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/삼청동_기온_202107_202206.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/삼청동_기온_202207_202212.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/삼청동_기온_202207_202212.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/삼청동_습도_201907_202006.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/삼청동_습도_201907_202006.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/삼청동_습도_202007_202106.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/삼청동_습도_202007_202106.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/삼청동_습도_202107_202206.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/삼청동_습도_202107_202206.csv에 저장했습니다.
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022/삼청동_습도_202207_202212.csv 파일은 이미 목표 행의 수와 일치하여 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/종로구2_날씨_2019_2022_Cleaned/삼청동_습도_202207_202212.csv에 저장했습니다.

## Merged

In [ ]:
import os
import pandas as pd

%cd /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Original/서대문구4_날씨_2019_2022


def merge_csvs_by_group(file_list, output_folder):
    # 파일들을 두 번째 언더바까지의 정보를 기준으로 그룹화
    groups = {}
    for csv_file in file_list:
        key = '_'.join(csv_file.split('_')[:2])
        if key not in groups:
            groups[key] = []
        groups[key].append(csv_file)

    # 각 그룹별로 파일들을 병합하여 저장
    for group_key, group_files in groups.items():
        # 빈 DataFrame 생성
        merged_df = pd.DataFrame()
        # 각 파일을 순환하면서 병합
        for csv_file in group_files:
            # 첫 번째 행을 제외하고 읽어옴
            df = pd.read_csv(csv_file)
            df.columns = ["date", "time", "value"]

            # "date" 열에서 "Start"를 포함하는 행을 삭제
            df = df[~df['date'].str.contains('Start')]

            merged_df = pd.concat([merged_df, df], ignore_index=True)

        # 파일 이름에 '2019_2022'를 추가하여 저장
        output_filename = f"{output_folder}/{group_key}_2019_2022.csv"
        merged_df.to_csv(output_filename, index=False)
        print(f"{group_key} 병합 및 저장 완료: {output_filename}")

/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Original/서대문구4_날씨_2019_2022

In [ ]:
file_list = sorted(os.listdir('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Original/서대문구4_날씨_2019_2022'))
file_list

['용신동_강수_201907_202006.csv',
 '용신동_강수_202007_202106.csv',
 '용신동_강수_202107_202206.csv',
 '용신동_강수_202207_202212.csv',
 '용신동_기온_201907_202006.csv',
 '용신동_기온_202007_202106.csv',
 '용신동_기온_202107_202206.csv',
 '용신동_기온_202207_202212.csv',
 '용신동_습도_201907_202006.csv',
 '용신동_습도_202007_202106.csv',
 '용신동_습도_202107_202206.csv',
 '용신동_습도_202207_202212.csv']

In [ ]:
# 결과를 저장할 폴더 각 자치구에 맞게 새로 생성
output_folder = "/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Merged/merged_서대문구4_날씨"
os.makedirs(output_folder, exist_ok=True)

# 함수 호출로 병합 수행
merge_csvs_by_group(file_list, output_folder)

용신동_강수 병합 및 저장 완료: /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Merged/merged_서대문구4_날씨/용신동_강수_2019_2022.csv
용신동_기온 병합 및 저장 완료: /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Merged/merged_서대문구4_날씨/용신동_기온_2019_2022.csv
용신동_습도 병합 및 저장 완료: /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Merged/merged_서대문구4_날씨/용신동_습도_2019_2022.csv

## Format

In [ ]:
import os
import pandas as pd

# 결과를 저장할 폴더 각 자치구에 맞게 새로 생성
output_folder = "/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Format/format_서대문구_추가"
os.makedirs(output_folder, exist_ok=True)

In [ ]:
file_list = sorted(os.listdir('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Merged/merged_서대문구4_날씨'))
file_list

['용신동_강수_2019_2022.csv',
 '용신동_기온_2019_2022.csv',
 '용신동_습도_2019_2022.csv']

In [ ]:
import os
import pandas as pd
import datetime

# Function to convert hour value to 'hh:mm' format
def convert_hour_format(time):
    if pd.notnull(time):
        try:
            hours = int(time) // 100
            minutes = int(time) % 100
            return f"{hours:02d}:{minutes:02d}"
        except ValueError:
            return 'NA'  # Return 'NA' if hour value is not a valid integer
    return 'NA'  # Return 'NA' for NaN values

# Function to perform the column renaming based on filename
def rename_columns(df, filename):
    df.rename(columns={df.columns[0]: 'date', 'time': 'time_temp'}, inplace=True)
    df['time'] = df['time_temp'].apply(convert_hour_format)
    df.drop(columns='time_temp', inplace=True)
    return df

# Function to modify the 'date' column with dates from 2019-07-01 to 2022-12-31
def modify_date_column(df):
    start_date = datetime.date(2019, 7, 1)
    end_date = datetime.date(2022, 12, 31)
    dates = [start_date + datetime.timedelta(days=i) for i in range((end_date - start_date).days + 1)]
    df['date'] = sorted(dates * 24)  # Sort the dates and repeat 24 times for each date
    return df

# Directory where the files are located
directory = '/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Merged/merged_서대문구4_날씨'
out_directory = '/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Format/format_서대문구_추가'

# Get the list of files in the directory
file_list = os.listdir(directory)

# Iterate through each file
for file in file_list:
    if file.endswith('.csv'):
        # Read the file into a DataFrame
        df = pd.read_csv(os.path.join(directory, file))

        # Get the filename without extension
        filename_without_extension = os.path.splitext(file)[0]

        # Perform column renaming based on filename
        df = rename_columns(df, filename_without_extension)

        # Reorder columns to have 'hour' as the second column
        if 'time' in df.columns:
            cols = list(df.columns)
            cols.insert(1, cols.pop(cols.index('time')))
            df = df[cols]

        # Modify the 'date' column with dates from 2019-07-01 to 2022-12-31
        df = modify_date_column(df)

        # Save the updated DataFrame back to the file
        df.to_csv(os.path.join(out_directory, file), index=False)

## 강수 기온 습도 합치기

In [ ]:
import os
import pandas as pd

# 데이터가 있는 경로를 지정합니다.
data_path = '/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Format/format_서대문구_추가'  # 데이터가 있는 경로로 변경해주세요.

# 데이터를 저장할 결과 디렉토리를 생성합니다.
result_path = '/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Final/final_서대문구_날씨_2019_2022'  # 결과를 저장할 경로로 변경해주세요.
os.makedirs(result_path, exist_ok=True)

# 첫 번째 언더바 전까지의 문자가 일치하는 CSV 파일들을 그룹화합니다.
grouped_files = {}
files = os.listdir(data_path)
files.sort()  # Sort filenames
for csv_file in files:
    file_name = csv_file.split('.')[0]
    group_name = '_'.join(file_name.split('_')[:1])
    if group_name not in grouped_files:
        grouped_files[group_name] = []
    grouped_files[group_name].append(csv_file)

# 그룹화된 파일들을 읽어들여서 결과 데이터프레임에 세 번째 열을 추가합니다.
result_df = pd.DataFrame()
for group_name, files in grouped_files.items():
    group_dfs = []
    first_file_read = False
    for idx, csv_file in enumerate(files):
        csv_path = os.path.join(data_path, csv_file)
        df = pd.read_csv(csv_path)
        column_name = csv_file.split('_')[1]  # 첫 번째 언더바와 두 번째 언더바 사이의 문자를 가져옵니다.
        if not first_file_read:
            # 첫 번째 파일의 경우 세 번째 열 이름을 변경합니다.
            df.columns.values[2] = column_name
            group_dfs.append(df)
            first_file_read = True
        else:
            group_dfs.append(df.iloc[:, 2].rename(column_name))
    merged_df = pd.concat(group_dfs, axis=1)
    result_df = pd.concat([result_df, merged_df], axis=0)

    # 새로운 파일 이름을 지정하여 결과를 저장합니다.
    new_file_name = f"{group_name}_강수기온습도_2019_2022.csv"
    result_file_path = os.path.join(result_path, new_file_name)
    merged_df.to_csv(result_file_path, index=False)

print("작업이 완료되었습니다. 결과는", result_path, "에 저장되었습니다.")

작업이 완료되었습니다. 결과는 /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Final/final_서대문구_날씨_2019_2022 에 저장되었습니다.

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Final/final_중랑구2_날씨_2019_2022/면목본동_강수기온습도_2019_2022.csv')
df

             date   time  강수      기온  습도
0      2019-07-01  00:00    0.0  25.299999   66.0
1      2019-07-01  01:00    0.0  25.799999   59.0
2      2019-07-01  02:00    0.0  27.200001   52.0
3      2019-07-01  03:00    0.0  27.400000   54.0
4      2019-07-01  04:00    0.0  28.200001   49.0
...           ...    ...    ...        ...    ...
30715  2022-12-31  19:00    0.0   1.800000   46.0
30716  2022-12-31  20:00    0.0   0.900000   49.0
30717  2022-12-31  21:00    0.0  -0.400000   58.0
30718  2022-12-31  22:00    0.0   0.000000   56.0
30719  2022-12-31  23:00    0.0   0.400000   57.0

[30720 rows x 5 columns]

## 행정동 코드 붙이기

In [ ]:
folder_path = '/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/Final/final_서대문구_날씨_2019_2022'
file_list = sorted(os.listdir(folder_path))
result = [filename.split('_')[0] for filename in file_list if '_' in filename]

# 결과 리스트 출력 (공백으로 구분)
result_str = ' '.join(result)
result_str

'신촌동 연희동 용신동 충현동 홍은2동'

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/서울시_행정동별_버스정류장+지하철역_개수.csv')
df.head()

     행정동코드   행정동  버스정류장_개수  지하철역_개수
0  1118051   가산동       170        3
1  1112071   진관동       138        1
2  1122066  양재1동       128        2
3  1114074   상암동       127        1
4  1122068   내곡동       118        1

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/행정동별_행정동코드.csv')
df1.head()

        행정동코드    행정동
0  1111051500  청운효자동
1  1111053000    사직동
2  1111054000    삼청동
3  1111055000    부암동
4  1111056000    평창동

In [ ]:
import os
import pandas as pd

# 폴더 경로와 행정동별_행정동코드.csv 파일 경로 설정
final_path = '/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/서대문구'

# 행정동 코드 파일 읽기
code_data = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/서울시_행정동별_버스정류장+지하철역_개수.csv')

# 행정동 이름 리스트 입력 받기
dong_names = input("행정동 이름을 순서대로 입력하세요 (공백으로 구분): ").split()

# 입력한 행정동 이름 개수와 파일 개수 일치 여부 확인
if len(dong_names) != len(file_list):
    print("입력한 행정동 개수와 파일 개수가 일치하지 않습니다.")
else:
    # 각 파일에 행정동 코드 열 추가하기
    for i, file_name in enumerate(file_list):
        # 파일 읽기
        file_path = os.path.join(folder_path, file_name)
        data = pd.read_csv(file_path)

        # 행정동 이름
        dong_name = dong_names[i]

        # 행정동 코드 찾기
        code_row = code_data[code_data['행정동'] == dong_name]
        if not code_row.empty:
            dong_code = code_row.iloc[0]['행정동코드']

            # 파일명에 행정동 코드 추가
            new_file_name = f"{dong_name}_weather_code.csv"

            # 파일에 행정동 코드 열 추가
            data.insert(0, '행정동코드', dong_code)

            # 수정된 데이터 저장
            new_file_path = os.path.join(final_path, new_file_name)
            data.to_csv(new_file_path, index=False)

행정동 이름을 순서대로 입력하세요 (공백으로 구분): 신촌동 연희동 용신동 충현동 홍은2동

In [ ]:
# 관악구 신사동/강남구 신사동 구분하기

# CSV 파일 경로 설정
csv_file_path = "/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/신사동_weather_code.csv"

# 열 이름 설정
target_column = "행정동코드"

# 바꿀 값 설정
new_value = "1123051" # 강남구 신사동

# CSV 파일 읽어오기
data = pd.read_csv(csv_file_path)

# 특정 열의 값을 변경
data[target_column] = new_value

# 변경된 데이터를 CSV 파일로 저장
data.to_csv("/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/신사동_weather_code.csv", index=False)

print("변경된 파일이 저장되었습니다.")

변경된 파일이 저장되었습니다.

## 각 자치구별 데이터 생성

In [ ]:
import os
import pandas as pd

%cd /content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code

# 폴더 내의 모든 CSV 파일 경로 가져오기
folder_path = '서대문구'
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

# CSV 파일들을 하나의 DataFrame으로 병합
combined_data = pd.DataFrame()
for csv_file in csv_files:
    csv_path = os.path.join(folder_path, csv_file)
    data = pd.read_csv(csv_path)
    combined_data = pd.concat([combined_data, data], axis=0)

# 결과를 하나의 CSV 파일로 저장
output_file = f'{folder_path}_weather_code.csv'
combined_data.to_csv(output_file, index=False)

print(f'CSV 파일들이 세로로 이어져서 {output_file} 파일로 저장되었습니다.')

/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code
CSV 파일들이 세로로 이어져서 서대문구_weather_code.csv 파일로 저장되었습니다.

In [ ]:
import natsort
filePath = '/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/'  # 폴더 주소를 입력

fileAll = os.listdir(filePath)
fileCsv = [filePath + file[:-4] for file in fileAll if file.endswith('.csv')] # csv에만 적용해라
fileCsv = natsort.natsorted(fileCsv)

for file in fileCsv:
    df = pd.read_csv(file + '.csv')
    print(file, len(df))

/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/강남구_weather_code 491520
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/강동구_weather_code 215040
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/강북구_weather_code 184320
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/강서구_weather_code 153600
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/관악구_weather_code 122880
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/광진구_weather_code 276480
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/구로구_weather_code 153600
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/금천구_weather_code 61440
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/노원구_weather_code 153600
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/도봉구_weather_code 61440
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/동대문구_weather_code 92160
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/동작구_weather_code 184320
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/마포구_weather_code 399360
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/서대문구_weather_code 153600
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/서초구_weather_code 430080
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/성동구_weather_code 184320
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/성북구_weather_code 368640
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/송파구_weather_code 215040
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/양천구_weather_code 122880
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/영등포구_weather_code 245760
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/용산구_weather_code 337920
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/은평구_weather_code 61440
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/종로구_weather_code 337920
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/중구_weather_code 337920
/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_code/중랑구_weather_code 30720

## 강수,기온,습도,미세먼지 병합

In [ ]:
# 1. '강남구_weather_code.csv' 파일을 읽어 '자치구' 열을 생성합니다.
district = '중랑구'
weather_code_df = pd.read_csv(f'/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_code/{district}_weather_code.csv', encoding='utf-8')
weather_code_df['자치구'] = district

# 2. 'final_micro_dust.csv' 파일을 읽어와 필요한 열을 추출합니다.
micro_dust_df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/final_micro_dust.csv', encoding='utf-8')

# 3. 두 데이터프레임을 'date', 'time', '자치구' 열을 기준으로 병합합니다.
merged_df = pd.merge(weather_code_df, micro_dust_df, on=['date', 'time', '자치구'],how='left')
merged_df = merged_df.drop('자치구', axis=1)

output_file = f'/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/{district}_weather.csv'
merged_df.to_csv(output_file, index=False)

In [ ]:
import natsort
import os
filePath = '/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/'  # 폴더 주소를 입력

fileAll = os.listdir(filePath)
fileCsv = [filePath + file[:-4] for file in fileAll if file.endswith('.csv')] # csv에만 적용해라
fileCsv = natsort.natsorted(fileCsv)

for file in fileCsv:
    df = pd.read_csv(file + '.csv')
    print(file, len(df))

/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/강남구_weather 491520
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/강동구_weather 215040
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/강북구_weather 184320
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/강서구_weather 153600
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/관악구_weather 122880
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/광진구_weather 276480
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/구로구_weather 153600
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/금천구_weather 61440
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/노원구_weather 153600
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/도봉구_weather 61440
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/동대문구_weather 92160
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/동작구_weather 184320
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/마포구_weather 399360
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/서대문구_weather 153600
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/서초구_weather 430080
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/성동구_weather 184320
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/성북구_weather 368640
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/송파구_weather 215040
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/양천구_weather 122880
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/영등포구_weather 245760
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/용산구_weather 337920
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/은평구_weather 61440
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/종로구_weather 337920
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/중구_weather 337920
/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/중랑구_weather 30720

In [ ]:
# 폴더 내의 모든 CSV 파일 경로 가져오기
folder_path = '/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/'
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

# CSV 파일들을 하나의 DataFrame으로 병합
combined_data = pd.DataFrame()
for csv_file in csv_files:
    csv_path = os.path.join(folder_path, csv_file)
    data = pd.read_csv(csv_path)
    combined_data = pd.concat([combined_data, data], axis=0)

combined_data['행정동코드'] = combined_data['행정동코드'].astype(str)
combined_data['행정동코드'] = combined_data['행정동코드'].str[:-2]

# 결과를 하나의 CSV 파일로 저장
combined_data.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/seoul_weather.csv', index=False)

print(f'CSV 파일들이 세로로 이어져서 {output_file} 파일로 저장되었습니다.')

CSV 파일들이 세로로 이어져서 /content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/중랑구_weather.csv 파일로 저장되었습니다.

In [ ]:
final_df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/weather_final/seoul_weather.csv')
final_df

,행정동코드,date,time,강수,기온,습도,미세먼지(PM10),초미세먼지(PM2.5),미세먼지등급,초미세먼지등급
0,11680690,2019-07-01,00:00,0.0,25.900000,66.0,42.0,34.0,1.0,1.0
1,11680690,2019-07-01,01:00,0.0,26.700001,59.0,48.0,39.0,1.0,2.0
2,11680690,2019-07-01,02:00,0.0,27.400000,58.0,44.0,36.0,1.0,2.0
3,11680690,2019-07-01,03:00,0.0,28.000000,52.0,38.0,29.0,1.0,1.0
4,11680690,2019-07-01,04:00,0.0,28.900000,48.0,35.0,28.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
5375995,11260540,2022-12-31,19:00,0.0,1.800000,46.0,57.0,42.0,1.0,2.0
5375996,11260540,2022-12-31,20:00,0.0,0.900000,49.0,54.0,39.0,1.0,2.0
5375997,11260540,2022-12-31,21:00,0.0,-0.400000,58.0,51.0,39.0,1.0,2.0
5375998,11260540,2022-12-31,22:00,0.0,0.000000,56.0,55.0,44.0,1.0,2.0
5375999,11260540,2022-12-31,23:00,0.0,0.400000,57.0,66.0,50.0,1.0,2.0

In [ ]:
len(combined_data['행정동코드'].unique())

175

## 행정동 코드 통합

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/행정동별_행정동코드.csv')
df1['행정동코드'] = df1['행정동코드'].astype(str)
df1['행정동코드'] = df1['행정동코드'].str[:-2]
df1.rename(columns={'행정동코드': '행안부코드'}, inplace=True)
df1.loc[df1['행안부코드'] == '11620685', '행정동'] = '신사동관악'

In [ ]:
replacement_dict = {'전농제2동': '전농2동', '장안제1동': '장안1동','장안제2동': '장안2동', '개포3동':'일원2동'}
df1['행정동'] = df1['행정동'].replace(replacement_dict)

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/서울시_행정동별_버스정류장+지하철역_개수.csv')
df2 = df2.drop(['지하철역_개수','버스정류장_개수'], axis=1)
df2['행정동코드'] = df2['행정동코드'].astype(str)
df2.rename(columns={'행정동코드': '통계청코드'}, inplace=True)
df2
df2.loc[df2['통계청코드'] == '1121068', '행정동'] = '신사동관악'

In [ ]:
# 두 개의 DataFrame을 가로로 병합
merged_df = pd.merge(df1, df2,on='행정동')
merged_df.loc[merged_df['행안부코드'] == '11620685', '행정동'] = '신사동'
merged_df
merged_df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/행정동코드_통합.csv', index=False)

In [ ]:
tot = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/행정동코드_통합.csv')
tot['행정동'].unique()

array(['청운효자동', '사직동', '삼청동', '부암동', '평창동', '무악동', '교남동', '가회동',
       '종로1·2·3·4가동', '종로5·6가동', '이화동', '혜화동', '창신1동', '창신2동', '창신3동',
       '숭인1동', '숭인2동', '소공동', '회현동', '명동', '필동', '장충동', '광희동', '을지로동',
       '신당동', '다산동', '약수동', '청구동', '신당5동', '동화동', '황학동', '중림동', '후암동',
       '용산2가동', '남영동', '청파동', '원효로1동', '원효로2동', '효창동', '용문동', '한강로동',
       '이촌1동', '이촌2동', '이태원1동', '이태원2동', '한남동', '서빙고동', '보광동', '왕십리2동',
       '왕십리도선동', '마장동', '사근동', '행당1동', '행당2동', '응봉동', '금호1가동', '금호2·3가동',
       '금호4가동', '옥수동', '성수1가1동', '성수1가2동', '성수2가1동', '성수2가3동', '송정동',
       '용답동', '화양동', '군자동', '중곡1동', '중곡2동', '중곡3동', '중곡4동', '능동', '광장동',
       '자양1동', '자양2동', '자양3동', '자양4동', '구의1동', '구의2동', '구의3동', '용신동',
       '제기동', '전농1동', '전농2동', '답십리1동', '답십리2동', '장안1동', '장안2동', '청량리동',
       '회기동', '휘경1동', '휘경2동', '이문1동', '이문2동', '면목2동', '면목4동', '면목5동',
       '면목본동', '면목7동', '면목3·8동', '상봉1동', '상봉2동', '중화1동', '중화2동', '묵1동',
       '묵2동', '망우본동', '망우3동', '신내1동', '신내2동', '성북동', '삼선동', '동선동', '돈암1동',
       '돈암2동', '안암동', '보문동', '정릉1동', '정릉2동', '정릉3동', '정릉4동', '길음1동',
       '길음2동', '종암동', '월곡1동', '월곡2동', '장위1동', '장위2동', '장위3동', '석관동',
       '삼양동', '미아동', '송중동', '송천동', '삼각산동', '번1동', '번2동', '번3동', '수유1동',
       '수유2동', '수유3동', '우이동', '인수동', '창1동', '창2동', '창3동', '창4동', '창5동',
       '도봉1동', '도봉2동', '쌍문1동', '쌍문2동', '쌍문3동', '쌍문4동', '방학1동', '방학2동',
       '방학3동', '월계1동', '월계2동', '월계3동', '공릉1동', '공릉2동', '하계1동', '하계2동',
       '중계본동', '중계1동', '중계4동', '중계2·3동', '상계1동', '상계2동', '상계3·4동', '상계5동',
       '상계6·7동', '상계8동', '상계9동', '상계10동', '녹번동', '불광1동', '불광2동', '갈현1동',
       '갈현2동', '구산동', '대조동', '응암1동', '응암2동', '응암3동', '역촌동', '신사1동',
       '신사2동', '증산동', '수색동', '진관동', '천연동', '북아현동', '충현동', '신촌동', '연희동',
       '홍제1동', '홍제3동', '홍제2동', '홍은1동', '홍은2동', '남가좌1동', '남가좌2동', '북가좌1동',
       '북가좌2동', '아현동', '공덕동', '도화동', '용강동', '대흥동', '염리동', '신수동', '서강동',
       '서교동', '합정동', '망원1동', '망원2동', '연남동', '성산1동', '성산2동', '상암동', '목1동',
       '목2동', '목3동', '목4동', '목5동', '신월1동', '신월2동', '신월3동', '신월4동', '신월5동',
       '신월6동', '신월7동', '신정1동', '신정2동', '신정3동', '신정4동', '신정6동', '신정7동',
       '염창동', '등촌1동', '등촌2동', '등촌3동', '화곡1동', '화곡2동', '화곡3동', '화곡4동',
       '화곡본동', '화곡6동', '화곡8동', '가양1동', '가양2동', '가양3동', '발산1동', '우장산동',
       '공항동', '방화1동', '방화2동', '방화3동', '신도림동', '구로1동', '구로2동', '구로3동',
       '구로4동', '구로5동', '가리봉동', '고척1동', '고척2동', '개봉1동', '개봉2동', '개봉3동',
       '오류1동', '오류2동', '수궁동', '항동', '가산동', '독산1동', '독산2동', '독산3동', '독산4동',
       '시흥1동', '시흥2동', '시흥3동', '시흥4동', '시흥5동', '영등포본동', '영등포동', '여의동',
       '당산1동', '당산2동', '도림동', '문래동', '양평1동', '양평2동', '신길1동', '신길3동',
       '신길4동', '신길5동', '신길6동', '신길7동', '대림1동', '대림2동', '대림3동', '노량진1동',
       '노량진2동', '상도1동', '상도2동', '상도3동', '상도4동', '흑석동', '사당1동', '사당2동',
       '사당3동', '사당4동', '사당5동', '대방동', '신대방1동', '신대방2동', '보라매동', '청림동',
       '성현동', '행운동', '낙성대동', '청룡동', '은천동', '중앙동', '인헌동', '남현동', '서원동',
       '신원동', '서림동', '신사동', '신림동', '난향동', '조원동', '대학동', '삼성동', '미성동',
       '난곡동', '서초1동', '서초2동', '서초3동', '서초4동', '잠원동', '반포본동', '반포1동',
       '반포2동', '반포3동', '반포4동', '방배본동', '방배1동', '방배2동', '방배3동', '방배4동',
       '양재1동', '양재2동', '내곡동', '논현1동', '논현2동', '압구정동', '청담동', '삼성1동',
       '삼성2동', '대치1동', '대치2동', '대치4동', '역삼1동', '역삼2동', '도곡1동', '도곡2동',
       '개포1동', '개포2동', '일원2동', '개포4동', '세곡동', '일원본동', '일원1동', '수서동',
       '풍납1동', '풍납2동', '거여1동', '거여2동', '마천1동', '마천2동', '방이1동', '방이2동',
       '오륜동', '오금동', '송파1동', '송파2동', '석촌동', '삼전동', '가락본동', '가락1동', '가락2동',
       '문정1동', '문정2동', '장지동', '위례동', '잠실본동', '잠실2동', '잠실3동', '잠실4동',
       '잠실6동', '잠실7동', '강일동', '상일1동', '상일2동', '명일1동', '명일2동', '고덕1동',
       '고덕2동', '암사1동', '암사2동', '암사3동', '천호1동', '천호2동', '천호3동', '성내1동',
       '성내2동', '성내3동', '길동', '둔촌1동', '둔촌2동'], dtype=object)

In [ ]:
tot[tot['행정동'] == '신사동']

        행안부코드  행정동    통계청코드
332  11620685  신사동  1121068
358  11680510  신사동  1123051

## 행정동코드 바꾸기

In [ ]:
final_df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/weather_final/seoul_weather.csv')
final_df.rename(columns={'행정동코드': '행안부코드'}, inplace=True)
code = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/행정동코드_통합.csv')
code.rename(columns={'통계청코드': '행정동코드'}, inplace=True)

In [ ]:
merged_df = pd.merge(final_df, code, on='행안부코드')

merged_df = merged_df.drop(['행안부코드','행정동'], axis=1)
merged_df = pd.concat([merged_df['행정동코드'], merged_df.drop('행정동코드', axis=1)], axis=1)
merged_df = merged_df.drop(['미세먼지(PM10)','초미세먼지(PM2.5)'], axis=1)

In [ ]:
merged_df[merged_df.isnull().any(axis=1)]

           행정동코드        date   time  강수      기온  습도  미세먼지등급  초미세먼지등급
4577280  1103051  2019-07-01  00:00    0.0  24.700001    NaN     1.0      1.0
4577281  1103051  2019-07-01  01:00    0.0  25.900000    NaN     1.0      2.0
4577282  1103051  2019-07-01  02:00    0.0  26.500000    NaN     1.0      2.0
4577283  1103051  2019-07-01  03:00    0.0  27.299999    NaN     1.0      1.0
4577284  1103051  2019-07-01  04:00    0.0  28.000000    NaN     0.0      1.0
...          ...         ...    ...    ...        ...    ...     ...      ...
5262117  1102068  2020-07-09  21:00    0.0  25.400000   74.0     NaN      NaN
5292836  1102057  2020-07-09  20:00    0.1  24.100000   77.0     NaN      NaN
5292837  1102057  2020-07-09  21:00    0.0  24.200001   75.0     NaN      NaN
5323556  1102054  2020-07-09  20:00    0.0  24.900000   83.0     NaN      NaN
5323557  1102054  2020-07-09  21:00    0.0  25.400000   74.0     NaN      NaN

[30742 rows x 8 columns]

In [ ]:
merged_df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/final_weather_seoul.csv', index=False)

In [ ]:
merged_df

           행정동코드        date   time  강수      기온  습도  미세먼지등급  초미세먼지등급
0        1123071  2019-07-01  00:00    0.0  25.900000   66.0     1.0      1.0
1        1123071  2019-07-01  01:00    0.0  26.700001   59.0     1.0      2.0
2        1123071  2019-07-01  02:00    0.0  27.400000   58.0     1.0      2.0
3        1123071  2019-07-01  03:00    0.0  28.000000   52.0     1.0      1.0
4        1123071  2019-07-01  04:00    0.0  28.900000   48.0     1.0      1.0
...          ...         ...    ...    ...        ...    ...     ...      ...
5375995  1107054  2022-12-31  19:00    0.0   1.800000   46.0     1.0      2.0
5375996  1107054  2022-12-31  20:00    0.0   0.900000   49.0     1.0      2.0
5375997  1107054  2022-12-31  21:00    0.0  -0.400000   58.0     1.0      2.0
5375998  1107054  2022-12-31  22:00    0.0   0.000000   56.0     1.0      2.0
5375999  1107054  2022-12-31  23:00    0.0   0.400000   57.0     1.0      2.0

[5376000 rows x 8 columns]

# allCO+date+code

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/FC/allFC_dong_cd_nm_trans.csv')
simple = df[['공연시설코드', '행정동코드']]
simple.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/FC/allFC_fc+code_only.csv', index=False)

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO+date.csv')
df1

,공연시설코드,공연장코드,공연코드,공연일시,공연회차,공연시작일자,공연종료일자,소요시간,장르명,세부장르명,출연진내용,기획제작사명,관람연령,아동공연 여부,축제 여부,내한공연 여부,오픈런 여부,좌석등급
0,FC222055,FC222055-02,PF300001,2022-04-26 20:00,1,2022-04-26,2022-06-30,105.0,연극,연극,"김주헌, 성태준, 김동원, 장인섭, 김용준, 이종무, 류원준 등",(주)연극열전(제작사),만 14세 이상,False,False,False,False,"R석(55000), S석(44000)"
1,FC222055,FC222055-02,PF300001,2022-04-27 20:00,1,2022-04-26,2022-06-30,105.0,연극,연극,"김주헌, 성태준, 김동원, 장인섭, 김용준, 이종무, 류원준 등",(주)연극열전(제작사),만 14세 이상,False,False,False,False,"R석(55000), S석(44000)"
2,FC222055,FC222055-02,PF300001,2022-04-28 20:00,1,2022-04-26,2022-06-30,105.0,연극,연극,"김주헌, 성태준, 김동원, 장인섭, 김용준, 이종무, 류원준 등",(주)연극열전(제작사),만 14세 이상,False,False,False,False,"R석(55000), S석(44000)"
3,FC222055,FC222055-02,PF300001,2022-04-29 20:00,1,2022-04-26,2022-06-30,105.0,연극,연극,"김주헌, 성태준, 김동원, 장인섭, 김용준, 이종무, 류원준 등",(주)연극열전(제작사),만 14세 이상,False,False,False,False,"R석(55000), S석(44000)"
4,FC222055,FC222055-02,PF300001,2022-04-30 15:00,1,2022-04-26,2022-06-30,105.0,연극,연극,"김주헌, 성태준, 김동원, 장인섭, 김용준, 이종무, 류원준 등",(주)연극열전(제작사),만 14세 이상,False,False,False,False,"R석(55000), S석(44000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195629,FC223751,FC223751-01,PF433739,2022-04-02 19:00,1,2022-04-02,2022-04-10,NaN,연극,연극,NaN,NaN,NaN,False,False,False,False,NaN
195630,FC223751,FC223751-01,PF433739,2022-04-03 14:00,1,2022-04-02,2022-04-10,NaN,연극,연극,NaN,NaN,NaN,False,False,False,False,NaN
195631,FC223751,FC223751-01,PF433739,2022-04-03 16:30,1,2022-04-02,2022-04-10,NaN,연극,연극,NaN,NaN,NaN,False,False,False,False,NaN
195632,FC223751,FC223751-01,PF433739,2022-04-10 14:00,1,2022-04-02,2022-04-10,NaN,연극,연극,NaN,NaN,NaN,False,False,False,False,NaN
195633,FC223751,FC223751-01,PF433739,2022-04-10 16:30,1,2022-04-02,2022-04-10,NaN,연극,연극,NaN,NaN,NaN,False,False,False,False,NaN

In [ ]:
merged_df = pd.merge(simple, df1, on='공연시설코드')
merged_df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO+date+code.csv', index=False)

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO+date+code.csv')
df2

# allCO work

In [ ]:
import pandas as pd
allCO = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO+date+code.csv')
allCO

,공연시설코드,행정동코드,공연장코드,공연코드,공연일시,공연회차,공연시작일자,공연종료일자,소요시간,장르명,세부장르명,출연진내용,기획제작사명,관람연령,아동공연 여부,축제 여부,내한공연 여부,오픈런 여부,좌석등급
0,FC223076,1113075,FC223076-01,PF301251,2022-04-22 19:30,1,2022-04-22,2022-04-30,80.0,연극,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",신촌문화발전소(서대문구청)(주최),만 7세 이상,False,False,False,False,전석(20000)
1,FC223076,1113075,FC223076-01,PF301251,2022-04-23 15:00,1,2022-04-22,2022-04-30,80.0,연극,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",신촌문화발전소(서대문구청)(주최),만 7세 이상,False,False,False,False,전석(20000)
2,FC223076,1113075,FC223076-01,PF301251,2022-04-26 19:30,1,2022-04-22,2022-04-30,80.0,연극,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",신촌문화발전소(서대문구청)(주최),만 7세 이상,False,False,False,False,전석(20000)
3,FC223076,1113075,FC223076-01,PF301251,2022-04-27 19:30,1,2022-04-22,2022-04-30,80.0,연극,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",신촌문화발전소(서대문구청)(주최),만 7세 이상,False,False,False,False,전석(20000)
4,FC223076,1113075,FC223076-01,PF301251,2022-04-28 19:30,1,2022-04-22,2022-04-30,80.0,연극,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",신촌문화발전소(서대문구청)(주최),만 7세 이상,False,False,False,False,전석(20000)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195629,FC224706,1125073,FC224706-01,PF425458,2022-12-29 11:30,1,2022-12-23,2022-12-31,50.0,뮤지컬,뮤지컬,NaN,"이지기획(주최), 피터폴앤메리(주관)",전체,True,False,False,False,전석(35000)
195630,FC224706,1125073,FC224706-01,PF425458,2022-12-30 11:30,1,2022-12-23,2022-12-31,50.0,뮤지컬,뮤지컬,NaN,"이지기획(주최), 피터폴앤메리(주관)",전체,True,False,False,False,전석(35000)
195631,FC224706,1125073,FC224706-01,PF425458,2022-12-31 11:30,1,2022-12-23,2022-12-31,50.0,뮤지컬,뮤지컬,NaN,"이지기획(주최), 피터폴앤메리(주관)",전체,True,False,False,False,전석(35000)
195632,FC224706,1125073,FC224706-01,PF425458,2022-12-31 14:00,1,2022-12-23,2022-12-31,50.0,뮤지컬,뮤지컬,NaN,"이지기획(주최), 피터폴앤메리(주관)",전체,True,False,False,False,전석(35000)
195633,FC224706,1125073,FC224706-01,PF425458,2022-12-31 16:00,1,2022-12-23,2022-12-31,50.0,뮤지컬,뮤지컬,NaN,"이지기획(주최), 피터폴앤메리(주관)",전체,True,False,False,False,전석(35000)

In [ ]:
allCO = allCO[['행정동코드','공연장코드',	'공연코드',	'공연일시',	'공연시작일자',	'공연종료일자',	'소요시간',	'세부장르명', '출연진내용','관람연령','아동공연 여부','축제 여부', '내한공연 여부',	'오픈런 여부','좌석등급']]

In [ ]:
allCO.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/work.csv', index=False)
work = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/work.csv')

## allCO work 공연기간

In [ ]:
work = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO+date+dong+sale+tropy+time+level+covid+weather.csv')
work

<ipython-input-19-3cf62caa45e7>:1: DtypeWarning: Columns (14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  work = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO+date+dong+sale+tropy+time+level+covid+weather.csv')

,행정동코드,공연시설코드,공연장코드,공연코드,공연일시,공연일,공연시간,공연시작일자,공연종료일자,소요시간,...,공연기간,휴일,시간대,좌석등급개수,확진자변화율,강수,기온,습도,미세먼지등급,초미세먼지등급
0,1101064,FC222055,FC222055-02,PF300001,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-26,2022-06-30,105.0,...,66,평일,밤,2,184.694520,0.0,13.200000,31.0,1.0,1.0
1,1101064,FC223420,FC223420-02,PF300003,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-19,2022-04-30,60.0,...,12,평일,밤,1,184.694520,0.0,13.200000,31.0,1.0,1.0
2,1101064,FC223671,FC223671-01,PF300257,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-22,2022-07-16,100.0,...,86,평일,밤,2,184.694520,0.0,13.200000,31.0,1.0,1.0
3,1101064,FC223740,FC223740-02,PF300778,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-01,2022-04-30,100.0,...,30,평일,밤,1,184.694520,0.0,13.200000,31.0,1.0,1.0
4,1101064,FC223740,FC223740-03,PF301247,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-26,2022-06-18,100.0,...,54,평일,밤,1,184.694520,0.0,13.200000,31.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196762,1118052,FC223787,FC223787-01,PF427890,2021-06-20 12:00:00,2021-06-20,12:00,2021-05-01,2021-06-26,55.0,...,57,주말,낮,1,-16.243655,0.0,21.200001,90.0,1.0,2.0
196763,1118052,FC223787,FC223787-01,PF427890,2021-06-26 12:00:00,2021-06-26,12:00,2021-05-01,2021-06-26,55.0,...,57,주말,낮,1,-2.230483,0.0,23.400000,82.0,0.0,1.0
196764,1118052,FC223787,FC223787-01,PF427890,2021-06-26 14:00:00,2021-06-26,14:00,2021-05-01,2021-06-26,55.0,...,57,주말,낮,1,-2.230483,0.0,22.100000,84.0,0.0,1.0
196765,1118052,FC223787,FC223787-01,PF427890,2021-06-26 16:00:00,2021-06-26,16:00,2021-05-01,2021-06-26,55.0,...,57,주말,낮,1,-2.230483,0.0,21.799999,86.0,0.0,1.0
196766,1105059,FC222232,FC222232-01,PF433731,2022-11-13 18:00:00,2022-11-13,18:00,2022-11-13,2022-11-13,100.0,...,1,주말,밤,1,-14.516427,0.0,9.500000,84.0,0.0,0.0

In [ ]:
work['공연시작일자'] = pd.to_datetime(work['공연시작일자'])
work['공연종료일자'] = pd.to_datetime(work['공연종료일자'])
work['공연기간'] = work['공연종료일자'] - work['공연시작일자']
work['공연기간'] = work['공연기간'].astype(str)
work['공연기간'] = work['공연기간'].str.replace(' days', '').astype(int)
work['공연기간'] = work['공연기간'] + 1

## allCO work 휴일 및 주말

In [ ]:
# '공연일시' 열의 값을 Datetime 형식으로 변환
work['공연일시'] = pd.to_datetime(work['공연일시'])

# '공연일시' 열에서 날짜 추출
work['날짜'] = work['공연일시'].dt.date

# '날짜' 열을 기준으로 요일(0: 월요일, 1: 화요일, ..., 6: 일요일) 추출
work['요일'] = work['공연일시'].dt.dayofweek

# 주말 여부 판단
work['휴일'] = work['요일'].apply(lambda x: '주말' if x == 5 or x == 6 else '평일')
work = work.drop(['요일'], axis=1)
work

,행정동코드,공연장코드,공연코드,공연일시,공연시작일자,공연종료일자,소요시간,세부장르명,출연진내용,관람연령,아동공연 여부,축제 여부,내한공연 여부,오픈런 여부,좌석등급,공연기간,날짜,휴일
0,1113075,FC223076-01,PF301251,2022-04-22 19:30:00,2022-04-22,2022-04-30,80.0,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",만 7세 이상,False,False,False,False,전석(20000),8 days,2022-04-22,평일
1,1113075,FC223076-01,PF301251,2022-04-23 15:00:00,2022-04-22,2022-04-30,80.0,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",만 7세 이상,False,False,False,False,전석(20000),8 days,2022-04-23,주말
2,1113075,FC223076-01,PF301251,2022-04-26 19:30:00,2022-04-22,2022-04-30,80.0,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",만 7세 이상,False,False,False,False,전석(20000),8 days,2022-04-26,평일
3,1113075,FC223076-01,PF301251,2022-04-27 19:30:00,2022-04-22,2022-04-30,80.0,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",만 7세 이상,False,False,False,False,전석(20000),8 days,2022-04-27,평일
4,1113075,FC223076-01,PF301251,2022-04-28 19:30:00,2022-04-22,2022-04-30,80.0,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",만 7세 이상,False,False,False,False,전석(20000),8 days,2022-04-28,평일
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195629,1125073,FC224706-01,PF425458,2022-12-29 11:30:00,2022-12-23,2022-12-31,50.0,뮤지컬,NaN,전체,True,False,False,False,전석(35000),8 days,2022-12-29,평일
195630,1125073,FC224706-01,PF425458,2022-12-30 11:30:00,2022-12-23,2022-12-31,50.0,뮤지컬,NaN,전체,True,False,False,False,전석(35000),8 days,2022-12-30,평일
195631,1125073,FC224706-01,PF425458,2022-12-31 11:30:00,2022-12-23,2022-12-31,50.0,뮤지컬,NaN,전체,True,False,False,False,전석(35000),8 days,2022-12-31,주말
195632,1125073,FC224706-01,PF425458,2022-12-31 14:00:00,2022-12-23,2022-12-31,50.0,뮤지컬,NaN,전체,True,False,False,False,전석(35000),8 days,2022-12-31,주말
195633,1125073,FC224706-01,PF425458,2022-12-31 16:00:00,2022-12-23,2022-12-31,50.0,뮤지컬,NaN,전체,True,False,False,False,전석(35000),8 days,2022-12-31,주말

In [ ]:
holiday = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/holiday_2018_2024.csv',usecols=['년','월','일','공휴일'])
holiday['날짜'] = holiday['년'].astype(str) + '-' + holiday['월'].astype(str).str.zfill(2) + '-' + holiday['일'].astype(str).str.zfill(2)
holiday['날짜'] = pd.to_datetime(holiday['날짜'])
holiday = holiday.drop(['년','월','일'], axis=1)
holiday

       공휴일         날짜
0       새해 2018-01-01
1       설날 2018-02-15
2       설날 2018-02-16
3       설날 2018-02-17
4      삼일절 2018-03-01
..     ...        ...
119     추석 2024-09-17
120     추석 2024-09-18
121    개천절 2024-10-03
122    한글날 2024-10-09
123  기독탄신일 2024-12-25

[124 rows x 2 columns]

In [ ]:
work['날짜'] = pd.to_datetime(work['날짜']).dt.date
holiday['날짜'] = pd.to_datetime(holiday['날짜']).dt.date

# '휴일' 열을 추가하고, 해당 날짜가 휴일 데이터프레임에 있는 경우 '공휴일' 값을 설정
work['휴일'] = np.where(work['날짜'].isin(holiday['날짜']), '공휴일', work['휴일'])
work = work.drop(['날짜'], axis=1)

In [ ]:
work[work['휴일'] == '공휴일']

,행정동코드,공연장코드,공연코드,공연일시,공연시작일자,공연종료일자,소요시간,세부장르명,출연진내용,관람연령,아동공연 여부,축제 여부,내한공연 여부,오픈런 여부,좌석등급,공연기간,휴일
164,1113075,FC223778-01,PF302316,2021-10-11 19:30:00,2021-10-11,2021-10-11,100.0,기악,이채영,만 7세 이상,False,False,False,False,전석(20000),0 days,공휴일
171,1113075,FC223778-01,PF302719,2021-10-04 19:30:00,2021-10-04,2021-10-04,90.0,기악,이수민,만 7세 이상,False,False,False,False,전석(20000),0 days,공휴일
285,1113075,FC223778-01,PF307042,2022-03-01 19:30:00,2022-03-01,2022-03-01,100.0,기악,김지은,만 7세 이상,False,False,False,False,전석(20000),0 days,공휴일
308,1113075,FC223778-01,PF308142,2022-03-01 15:00:00,2022-03-01,2022-03-01,90.0,기악,조주연,만 7세 이상,False,False,False,False,전석(20000),0 days,공휴일
334,1113075,FC223778-01,PF309257,2022-03-09 19:00:00,2022-03-09,2022-03-09,90.0,기악,"최혜경, 이지현",만 7세 이상,False,False,False,False,전석(20000),0 days,공휴일
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195494,1115070,FC224162-01,PF312255,2022-05-05 16:00:00,2022-05-05,2022-05-05,50.0,인형극,"지근우, 안주영",만 3세 이상,True,False,False,False,전석(20000),0 days,공휴일
195510,1115070,FC224162-01,PF423621,2022-12-25 11:00:00,2022-12-22,2023-01-21,60.0,뮤지컬,NaN,만 2세 이상,True,False,False,False,전석(50000),30 days,공휴일
195511,1115070,FC224162-01,PF423621,2022-12-25 14:00:00,2022-12-22,2023-01-21,60.0,뮤지컬,NaN,만 2세 이상,True,False,False,False,전석(50000),30 days,공휴일
195625,1125073,FC224706-01,PF425458,2022-12-25 11:30:00,2022-12-23,2022-12-31,50.0,뮤지컬,NaN,전체,True,False,False,False,전석(35000),8 days,공휴일
195626,1125073,FC224706-01,PF425458,2022-12-25 14:00:00,2022-12-23,2022-12-31,50.0,뮤지컬,NaN,전체,True,False,False,False,전석(35000),8 days,공휴일

In [ ]:
work['공연일시'] = pd.to_datetime(work['공연일시'])

# 시간대 분류 함수 정의
def classify_time_period(time):
    if 5 <= time.hour < 12:
        return '아침'
    elif 12 <= time.hour < 18:
        return '낮'
    else:
        return '밤'

# '시간대' 열 생성
work['시간대'] = work['공연일시'].apply(classify_time_period)

In [ ]:
work['공연일'] = pd.to_datetime(work['공연일시']).dt.date
work['공연시간'] = pd.to_datetime(work['공연일시']).dt.time
work = work[['행정동코드','공연장코드',	'공연코드',	'공연일시','공연일','공연시간','공연시작일자','공연종료일자',	'소요시간',	'세부장르명', '출연진내용','관람연령','아동공연 여부','축제 여부', '내한공연 여부',	'오픈런 여부','좌석등급','공연기간','휴일','시간대']]
work['공연시간'] = pd.to_datetime(work['공연시간'], format='%H:%M:%S').dt.strftime('%H:%M')

In [ ]:
work

,행정동코드,공연장코드,공연코드,공연일시,공연일,공연시간,공연시작일자,공연종료일자,소요시간,세부장르명,출연진내용,관람연령,아동공연 여부,축제 여부,내한공연 여부,오픈런 여부,좌석등급,공연기간,휴일,시간대
0,1113075,FC223076-01,PF301251,2022-04-22 19:30:00,2022-04-22,19:30,2022-04-22,2022-04-30,80.0,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",만 7세 이상,False,False,False,False,전석(20000),9,평일,밤
1,1113075,FC223076-01,PF301251,2022-04-23 15:00:00,2022-04-23,15:00,2022-04-22,2022-04-30,80.0,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",만 7세 이상,False,False,False,False,전석(20000),9,주말,낮
2,1113075,FC223076-01,PF301251,2022-04-26 19:30:00,2022-04-26,19:30,2022-04-22,2022-04-30,80.0,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",만 7세 이상,False,False,False,False,전석(20000),9,평일,밤
3,1113075,FC223076-01,PF301251,2022-04-27 19:30:00,2022-04-27,19:30,2022-04-22,2022-04-30,80.0,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",만 7세 이상,False,False,False,False,전석(20000),9,평일,밤
4,1113075,FC223076-01,PF301251,2022-04-28 19:30:00,2022-04-28,19:30,2022-04-22,2022-04-30,80.0,연극,"최정화, 임윤진, 정제이, 오수혜, 장석환",만 7세 이상,False,False,False,False,전석(20000),9,평일,밤
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195629,1125073,FC224706-01,PF425458,2022-12-29 11:30:00,2022-12-29,11:30,2022-12-23,2022-12-31,50.0,뮤지컬,NaN,전체,True,False,False,False,전석(35000),9,평일,아침
195630,1125073,FC224706-01,PF425458,2022-12-30 11:30:00,2022-12-30,11:30,2022-12-23,2022-12-31,50.0,뮤지컬,NaN,전체,True,False,False,False,전석(35000),9,평일,아침
195631,1125073,FC224706-01,PF425458,2022-12-31 11:30:00,2022-12-31,11:30,2022-12-23,2022-12-31,50.0,뮤지컬,NaN,전체,True,False,False,False,전석(35000),9,주말,아침
195632,1125073,FC224706-01,PF425458,2022-12-31 14:00:00,2022-12-31,14:00,2022-12-23,2022-12-31,50.0,뮤지컬,NaN,전체,True,False,False,False,전석(35000),9,주말,낮
195633,1125073,FC224706-01,PF425458,2022-12-31 16:00:00,2022-12-31,16:00,2022-12-23,2022-12-31,50.0,뮤지컬,NaN,전체,True,False,False,False,전석(35000),9,주말,낮

## allCO work 좌석등급 개수

In [ ]:
allCO = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO_230817.csv')
allCO

<ipython-input-20-bec9638b3b71>:1: DtypeWarning: Columns (14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  allCO = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO+date+dong+sale+tropy+time+level+covid+weather.csv')

,행정동코드,공연시설코드,공연장코드,공연코드,공연일시,공연일,공연시간,공연시작일자,공연종료일자,소요시간,...,공연기간,휴일,시간대,좌석등급개수,확진자변화율,강수,기온,습도,미세먼지등급,초미세먼지등급
0,1101064,FC222055,FC222055-02,PF300001,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-26,2022-06-30,105.0,...,66,평일,밤,2,184.694520,0.0,13.200000,31.0,1.0,1.0
1,1101064,FC223420,FC223420-02,PF300003,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-19,2022-04-30,60.0,...,12,평일,밤,1,184.694520,0.0,13.200000,31.0,1.0,1.0
2,1101064,FC223671,FC223671-01,PF300257,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-22,2022-07-16,100.0,...,86,평일,밤,2,184.694520,0.0,13.200000,31.0,1.0,1.0
3,1101064,FC223740,FC223740-02,PF300778,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-01,2022-04-30,100.0,...,30,평일,밤,1,184.694520,0.0,13.200000,31.0,1.0,1.0
4,1101064,FC223740,FC223740-03,PF301247,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-26,2022-06-18,100.0,...,54,평일,밤,1,184.694520,0.0,13.200000,31.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196762,1118052,FC223787,FC223787-01,PF427890,2021-06-20 12:00:00,2021-06-20,12:00,2021-05-01,2021-06-26,55.0,...,57,주말,낮,1,-16.243655,0.0,21.200001,90.0,1.0,2.0
196763,1118052,FC223787,FC223787-01,PF427890,2021-06-26 12:00:00,2021-06-26,12:00,2021-05-01,2021-06-26,55.0,...,57,주말,낮,1,-2.230483,0.0,23.400000,82.0,0.0,1.0
196764,1118052,FC223787,FC223787-01,PF427890,2021-06-26 14:00:00,2021-06-26,14:00,2021-05-01,2021-06-26,55.0,...,57,주말,낮,1,-2.230483,0.0,22.100000,84.0,0.0,1.0
196765,1118052,FC223787,FC223787-01,PF427890,2021-06-26 16:00:00,2021-06-26,16:00,2021-05-01,2021-06-26,55.0,...,57,주말,낮,1,-2.230483,0.0,21.799999,86.0,0.0,1.0
196766,1105059,FC222232,FC222232-01,PF433731,2022-11-13 18:00:00,2022-11-13,18:00,2022-11-13,2022-11-13,100.0,...,1,주말,밤,1,-14.516427,0.0,9.500000,84.0,0.0,0.0

In [ ]:
allCO['좌석등급'].unique().tolist()

In [ ]:
import pandas as pd
import re
# NaN 값을 빈 문자열로 대체
allCO['좌석등급'].fillna('', inplace=True)

# 괄호 내용 제거 함수 정의
def remove_brackets_and_content(match):
    return ''

# '좌석등급' 열의 데이터에서 괄호 안의 내용을 제거
allCO['좌석등급'] = allCO['좌석등급'].apply(lambda x: re.sub(r'\((.*?)\)', remove_brackets_and_content, x))

# 각 행에 대해 고유한 값 개수 세기
def count_unique_values(row):
    values = row.split(', ')
    return len(set(values))

allCO['좌석등급개수'] = allCO['좌석등급'].apply(count_unique_values)

In [ ]:
allCO

,Unnamed: 0,행정동코드,공연시설코드,공연장코드,공연코드,공연일시,공연일,공연시간,공연시작일자,공연종료일자,...,축제 여부,내한공연 여부,오픈런 여부,좌석등급,할인종류개수,수상실적개수,공연기간,휴일,시간대,좌석등급개수
0,0,1101064,FC222055,FC222055-02,PF300001,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-26,2022-06-30,...,False,False,False,"R석, S석",0,0,66,평일,밤,2
1,1,1101064,FC222055,FC222055-02,PF300001,2022-04-27 20:00:00,2022-04-27,20:00,2022-04-26,2022-06-30,...,False,False,False,"R석, S석",0,0,66,평일,밤,2
2,2,1101064,FC222055,FC222055-02,PF300001,2022-04-28 20:00:00,2022-04-28,20:00,2022-04-26,2022-06-30,...,False,False,False,"R석, S석",0,0,66,평일,밤,2
3,3,1101064,FC222055,FC222055-02,PF300001,2022-04-29 20:00:00,2022-04-29,20:00,2022-04-26,2022-06-30,...,False,False,False,"R석, S석",0,0,66,평일,밤,2
4,4,1101064,FC222055,FC222055-02,PF300001,2022-04-30 15:00:00,2022-04-30,15:00,2022-04-26,2022-06-30,...,False,False,False,"R석, S석",0,0,66,주말,낮,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196762,196762,1101064,FC223751,FC223751-01,PF433739,2022-04-02 19:00:00,2022-04-02,19:00,2022-04-02,2022-04-10,...,False,False,False,,1,0,9,주말,밤,1
196763,196763,1101064,FC223751,FC223751-01,PF433739,2022-04-03 14:00:00,2022-04-03,14:00,2022-04-02,2022-04-10,...,False,False,False,,1,0,9,주말,낮,1
196764,196764,1101064,FC223751,FC223751-01,PF433739,2022-04-03 16:30:00,2022-04-03,16:30,2022-04-02,2022-04-10,...,False,False,False,,1,0,9,주말,낮,1
196765,196765,1101064,FC223751,FC223751-01,PF433739,2022-04-10 14:00:00,2022-04-10,14:00,2022-04-02,2022-04-10,...,False,False,False,,1,0,9,주말,낮,1
196766,196766,1101064,FC223751,FC223751-01,PF433739,2022-04-10 16:30:00,2022-04-10,16:30,2022-04-02,2022-04-10,...,False,False,False,,1,0,9,주말,낮,1

In [ ]:
allCO.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO+date+dong+sale+tropy+time+level.csv', index=False)

## allCO work 좌석등급 개수 (좌석등급 null이면 다시 개수 null 처리)

In [ ]:
allCO = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO+date+dong+sale+tropy+time+level+covid+weather.csv',usecols=['공연코드','공연기간','좌석등급','좌석등급개수'])
allCO = allCO.drop_duplicates()
allCO

            공연코드    좌석등급  공연기간  좌석등급개수
0       PF300001  R석, S석    66       2
1       PF300003      전석    12       1
2       PF300257  R석, S석    86       2
3       PF300778      전석    30       1
4       PF301247      전석    54       1
...          ...     ...   ...     ...
196575  PF427510     NaN     1       1
196576  PF427511     NaN     1       1
196577  PF427582    전석무료     1       1
196578  PF427659     NaN     1       1
196579  PF427814      전석    10       1

[21303 rows x 4 columns]

In [ ]:
clust = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/coco_clust_21303.csv')
clust

           공연코드   평균사전예매율   평균당일예매율         총매출액   총티켓예매수
0      PF300001  0.953146  0.046854  441799300.0  14490.0
1      PF300002  1.000000  0.000000     200000.0     20.0
2      PF300003  1.000000  0.000000   13542000.0    741.0
3      PF300004  0.945274  0.054726   11048000.0    456.0
4      PF300005  1.000000  0.000000          0.0    299.0
...         ...       ...       ...          ...      ...
21298  PF428428  1.000000  0.000000   16368000.0    248.0
21299  PF433731  0.941790  0.058210   19890000.0   1151.0
21300  PF433737  0.808511  0.191489     795000.0    141.0
21301  PF433738  1.000000  0.000000     156000.0    249.0
21302  PF433739  0.640060  0.359940    3692000.0    219.0

[21303 rows x 5 columns]

In [ ]:
merged_df = pd.merge(clust, allCO, on='공연코드')
merged_df

,공연코드,평균사전예매율,평균당일예매율,총매출액,총티켓예매수,좌석등급,공연기간,좌석등급개수
0,PF300001,0.953146,0.046854,441799300.0,14490.0,"R석, S석",66,2
1,PF300002,1.000000,0.000000,200000.0,20.0,전석,1,1
2,PF300003,1.000000,0.000000,13542000.0,741.0,전석,12,1
3,PF300004,0.945274,0.054726,11048000.0,456.0,"R석, S석",2,2
4,PF300005,1.000000,0.000000,0.0,299.0,전석무료,1,1
...,...,...,...,...,...,...,...,...
21298,PF428428,1.000000,0.000000,16368000.0,248.0,NaN,1,1
21299,PF433731,0.941790,0.058210,19890000.0,1151.0,NaN,1,1
21300,PF433737,0.808511,0.191489,795000.0,141.0,전석,1,1
21301,PF433738,1.000000,0.000000,156000.0,249.0,NaN,1,1
21302,PF433739,0.640060,0.359940,3692000.0,219.0,NaN,9,1

In [ ]:
merged_df.loc[merged_df['좌석등급'].isnull(), '좌석등급개수'] = None
merged_df

,공연코드,평균사전예매율,평균당일예매율,총매출액,총티켓예매수,좌석등급,공연기간,좌석등급개수
0,PF300001,0.953146,0.046854,441799300.0,14490.0,"R석, S석",66,2.0
1,PF300002,1.000000,0.000000,200000.0,20.0,전석,1,1.0
2,PF300003,1.000000,0.000000,13542000.0,741.0,전석,12,1.0
3,PF300004,0.945274,0.054726,11048000.0,456.0,"R석, S석",2,2.0
4,PF300005,1.000000,0.000000,0.0,299.0,전석무료,1,1.0
...,...,...,...,...,...,...,...,...
21298,PF428428,1.000000,0.000000,16368000.0,248.0,NaN,1,NaN
21299,PF433731,0.941790,0.058210,19890000.0,1151.0,NaN,1,NaN
21300,PF433737,0.808511,0.191489,795000.0,141.0,전석,1,1.0
21301,PF433738,1.000000,0.000000,156000.0,249.0,NaN,1,NaN
21302,PF433739,0.640060,0.359940,3692000.0,219.0,NaN,9,NaN

In [ ]:
merged_df = merged_df.drop(['좌석등급'], axis = 1)

In [ ]:
merged_df

           공연코드   평균사전예매율   평균당일예매율         총매출액   총티켓예매수  공연기간  좌석등급개수
0      PF300001  0.953146  0.046854  441799300.0  14490.0    66     2.0
1      PF300002  1.000000  0.000000     200000.0     20.0     1     1.0
2      PF300003  1.000000  0.000000   13542000.0    741.0    12     1.0
3      PF300004  0.945274  0.054726   11048000.0    456.0     2     2.0
4      PF300005  1.000000  0.000000          0.0    299.0     1     1.0
...         ...       ...       ...          ...      ...   ...     ...
21298  PF428428  1.000000  0.000000   16368000.0    248.0     1     NaN
21299  PF433731  0.941790  0.058210   19890000.0   1151.0     1     NaN
21300  PF433737  0.808511  0.191489     795000.0    141.0     1     1.0
21301  PF433738  1.000000  0.000000     156000.0    249.0     1     NaN
21302  PF433739  0.640060  0.359940    3692000.0    219.0     9     NaN

[21303 rows x 7 columns]

In [ ]:
merged_df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/coco_clust_final.csv', index=False)
merged_df

,공연시설코드,공연장코드,공연코드,공연횟수,좌석수,사전예매건수,사전취소건수,당일예매건수,당일취소건수,전체예매건수,...,교통개수,무대시설,공연기간,좌석등급개수,평일평균횟수,주말평균횟수,공휴일평균횟수,할인종류개수,할인예매건수,수상실적개수
0,FC222005,FC222005-02,PF374942,4,318.0,27,12,0,0,27,...,28,2,2,2.0,2.0,2.0,0.0,3,6,0
1,FC222005,FC222005-03,PF351529,154,333.0,879,176,136,0,1015,...,28,2,326,2.0,1.5,1.5,1.0,7,255,0
2,FC222005,FC222005-03,PF424187,2,333.0,34,7,0,0,34,...,28,2,8,2.0,0.0,1.0,0.0,0,0,0
3,FC222005,FC222005-04,PF361283,258,334.0,4194,1223,348,18,4542,...,28,2,363,3.0,1.5,1.5,1.5,11,300,0
4,FC222005,FC222005-04,PF422043,14,334.0,65,25,0,0,65,...,28,2,12,1.0,1.0,2.0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18731,FC225489,FC225489-01,PF310442,1,128.0,66,4,0,0,66,...,49,1,1,2.0,0.0,1.0,0.0,0,0,0
18732,FC225489,FC225489-01,PF310552,3,128.0,34,5,10,0,44,...,49,1,29,1.0,1.0,1.0,0.0,4,28,0
18733,FC225489,FC225489-01,PF316039,2,128.0,12,1,1,0,13,...,49,1,36,1.0,1.0,0.0,0.0,0,0,0
18734,FC225489,FC225489-01,PF424689,2,128.0,9,4,4,0,13,...,49,1,29,1.0,1.0,0.0,0.0,2,12,0
18735,FC225541,FC225541-01,PF426902,1,171.0,0,0,167,0,167,...,49,1,1,1.0,1.0,0.0,0.0,0,0,0

# COVID DATA

In [ ]:
covid = pd.read_excel('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/korea_covid.xlsx')
covid.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/korea_covid.csv', index=False)

In [ ]:
covid = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/korea_covid.csv',usecols=['서울시 기준일','서울시 확진자','서울시 추가 확진'])
covid.rename(columns={'서울시 기준일': '공연일','서울시 확진자': '총확진자','서울시 추가 확진':'추가확진자'}, inplace=True)

ValueError: ignored

In [ ]:
def remove_decimal(s):
    return s.rsplit('.', 1)[0]

# '공연일' 열에 함수 적용
covid['공연일'] = covid['공연일'].apply(remove_decimal)

In [ ]:
def convert_date_format(date_str):
    # 주어진 형식으로 날짜 파싱
    date = pd.to_datetime(date_str, format='%y.%m.%d')
    # 년도를 4자리로 변경한 뒤 문자열로 반환
    return date.strftime('%Y.%m.%d')

# '공연일' 칼럼에 변환 적용
covid.loc[1189:, '공연일'] = covid.loc[1189:, '공연일'].apply(convert_date_format)

In [ ]:
covid['공연일'] = pd.to_datetime(covid['공연일'], format='%Y-%m-%d')
covid = covid[covid['공연일'] <= '2022-12-31']

# '공연일' 열을 기준으로 오름차순으로 정렬
covid = covid.sort_values(by='공연일')

In [ ]:
covid[covid['확진자변화율'] == np.inf]

Empty DataFrame
Columns: [공연일, 총확진자, 추가확진자, 확진자변화율]
Index: []

In [ ]:
covid['확진자변화율'] = covid['추가확진자'].diff() / covid['추가확진자'].shift(1) * 100
covid['확진자변화율'] = covid['확진자변화율'].replace([np.inf, -np.inf], np.nan)

In [ ]:
covid = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/seoul_covid.csv')
covid

             공연일     총확진자    추가확진자      확진자변화율
0     2020-02-05        8      0.0         NaN
1     2020-02-06       11      0.0         NaN
2     2020-02-07       10      0.0         NaN
3     2020-02-08       10      0.0         NaN
4     2020-02-09       10      0.0         NaN
...          ...      ...      ...         ...
1056  2022-12-27  5610852  18725.0  422.315202
1057  2022-12-28  5626635  15783.0  -15.711615
1058  2022-12-29  5640031  13396.0  -15.123867
1059  2022-12-30  5651699  11668.0  -12.899373
1060  2022-12-31  5663251  11601.0   -0.574220

[1061 rows x 4 columns]

In [ ]:
covid.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/seoul_covid.csv', index=False)

# allCO

## allCO + COVID

In [ ]:
allCO = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO+date+dong+sale+tropy+time+level.csv')

<ipython-input-9-029ecd2e0b73>:1: DtypeWarning: Columns (15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  allCO = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO+date+dong+sale+tropy+time+level.csv')

In [ ]:
allcovid = pd.merge(allCO, covid, on='공연일',how='left')
allcovid = allcovid.drop(['총확진자','추가확진자'], axis = 1)
allcovid

,Unnamed: 0,행정동코드,공연시설코드,공연장코드,공연코드,공연일시,공연일,공연시간,공연시작일자,공연종료일자,...,내한공연 여부,오픈런 여부,좌석등급,할인종류개수,수상실적개수,공연기간,휴일,시간대,좌석등급개수,확진자변화율
0,0,1101064,FC222055,FC222055-02,PF300001,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-26,2022-06-30,...,False,False,"R석, S석",0,0,66,평일,밤,2,184.694520
1,1,1101064,FC222055,FC222055-02,PF300001,2022-04-27 20:00:00,2022-04-27,20:00,2022-04-26,2022-06-30,...,False,False,"R석, S석",0,0,66,평일,밤,2,-15.066372
2,2,1101064,FC222055,FC222055-02,PF300001,2022-04-28 20:00:00,2022-04-28,20:00,2022-04-26,2022-06-30,...,False,False,"R석, S석",0,0,66,평일,밤,2,-20.908223
3,3,1101064,FC222055,FC222055-02,PF300001,2022-04-29 20:00:00,2022-04-29,20:00,2022-04-26,2022-06-30,...,False,False,"R석, S석",0,0,66,평일,밤,2,-15.182786
4,4,1101064,FC222055,FC222055-02,PF300001,2022-04-30 15:00:00,2022-04-30,15:00,2022-04-26,2022-06-30,...,False,False,"R석, S석",0,0,66,주말,낮,2,-16.450945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196762,196762,1101064,FC223751,FC223751-01,PF433739,2022-04-02 19:00:00,2022-04-02,19:00,2022-04-02,2022-04-10,...,False,False,NaN,1,0,9,주말,밤,1,-5.885879
196763,196763,1101064,FC223751,FC223751-01,PF433739,2022-04-03 14:00:00,2022-04-03,14:00,2022-04-02,2022-04-10,...,False,False,NaN,1,0,9,주말,낮,1,-13.485916
196764,196764,1101064,FC223751,FC223751-01,PF433739,2022-04-03 16:30:00,2022-04-03,16:30,2022-04-02,2022-04-10,...,False,False,NaN,1,0,9,주말,낮,1,-13.485916
196765,196765,1101064,FC223751,FC223751-01,PF433739,2022-04-10 14:00:00,2022-04-10,14:00,2022-04-02,2022-04-10,...,False,False,NaN,1,0,9,주말,낮,1,-10.578589
196766,196766,1101064,FC223751,FC223751-01,PF433739,2022-04-10 16:30:00,2022-04-10,16:30,2022-04-02,2022-04-10,...,False,False,NaN,1,0,9,주말,낮,1,-10.578589

## allCO+COVID+Weather

In [ ]:
allcovid = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO+date+dong+sale+tropy+time+level+covid.csv')

FileNotFoundError: ignored

In [ ]:
weather = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/Weather/final_weather_seoul.csv')

In [ ]:
from datetime import datetime
allcovid['공연정각'] = allcovid['공연시간'].apply(lambda x: datetime.strptime(x, '%H:%M').replace(minute=0).strftime('%H:%M'))
weather.rename(columns={'date': '공연일','time':'공연정각'}, inplace=True)

In [ ]:
allcovid

,Unnamed: 0,행정동코드,공연시설코드,공연장코드,공연코드,공연일시,공연일,공연시간,공연시작일자,공연종료일자,...,오픈런 여부,좌석등급,할인종류개수,수상실적개수,공연기간,휴일,시간대,좌석등급개수,확진자변화율,공연정각
0,0,1101064,FC222055,FC222055-02,PF300001,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-26,2022-06-30,...,False,"R석, S석",0,0,66,평일,밤,2,184.694520,20:00
1,1,1101064,FC222055,FC222055-02,PF300001,2022-04-27 20:00:00,2022-04-27,20:00,2022-04-26,2022-06-30,...,False,"R석, S석",0,0,66,평일,밤,2,-15.066372,20:00
2,2,1101064,FC222055,FC222055-02,PF300001,2022-04-28 20:00:00,2022-04-28,20:00,2022-04-26,2022-06-30,...,False,"R석, S석",0,0,66,평일,밤,2,-20.908223,20:00
3,3,1101064,FC222055,FC222055-02,PF300001,2022-04-29 20:00:00,2022-04-29,20:00,2022-04-26,2022-06-30,...,False,"R석, S석",0,0,66,평일,밤,2,-15.182786,20:00
4,4,1101064,FC222055,FC222055-02,PF300001,2022-04-30 15:00:00,2022-04-30,15:00,2022-04-26,2022-06-30,...,False,"R석, S석",0,0,66,주말,낮,2,-16.450945,15:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196762,196762,1101064,FC223751,FC223751-01,PF433739,2022-04-02 19:00:00,2022-04-02,19:00,2022-04-02,2022-04-10,...,False,NaN,1,0,9,주말,밤,1,-5.885879,19:00
196763,196763,1101064,FC223751,FC223751-01,PF433739,2022-04-03 14:00:00,2022-04-03,14:00,2022-04-02,2022-04-10,...,False,NaN,1,0,9,주말,낮,1,-13.485916,14:00
196764,196764,1101064,FC223751,FC223751-01,PF433739,2022-04-03 16:30:00,2022-04-03,16:30,2022-04-02,2022-04-10,...,False,NaN,1,0,9,주말,낮,1,-13.485916,16:00
196765,196765,1101064,FC223751,FC223751-01,PF433739,2022-04-10 14:00:00,2022-04-10,14:00,2022-04-02,2022-04-10,...,False,NaN,1,0,9,주말,낮,1,-10.578589,14:00
196766,196766,1101064,FC223751,FC223751-01,PF433739,2022-04-10 16:30:00,2022-04-10,16:30,2022-04-02,2022-04-10,...,False,NaN,1,0,9,주말,낮,1,-10.578589,16:00

In [ ]:
weather

           행정동코드         공연일   공연정각  강수      기온  습도  미세먼지등급  초미세먼지등급
0        1123071  2019-07-01  00:00    0.0  25.900000   66.0     1.0      1.0
1        1123071  2019-07-01  01:00    0.0  26.700001   59.0     1.0      2.0
2        1123071  2019-07-01  02:00    0.0  27.400000   58.0     1.0      2.0
3        1123071  2019-07-01  03:00    0.0  28.000000   52.0     1.0      1.0
4        1123071  2019-07-01  04:00    0.0  28.900000   48.0     1.0      1.0
...          ...         ...    ...    ...        ...    ...     ...      ...
5375995  1107054  2022-12-31  19:00    0.0   1.800000   46.0     1.0      2.0
5375996  1107054  2022-12-31  20:00    0.0   0.900000   49.0     1.0      2.0
5375997  1107054  2022-12-31  21:00    0.0  -0.400000   58.0     1.0      2.0
5375998  1107054  2022-12-31  22:00    0.0   0.000000   56.0     1.0      2.0
5375999  1107054  2022-12-31  23:00    0.0   0.400000   57.0     1.0      2.0

[5376000 rows x 8 columns]

In [ ]:
all_covid_weather = pd.merge(allcovid, weather, on=['행정동코드','공연일','공연정각'],how="inner")
all_covid_weather = all_covid_weather.drop(['공연정각'], axis = 1)

In [ ]:
all_covid_weather

,Unnamed: 0,행정동코드,공연시설코드,공연장코드,공연코드,공연일시,공연일,공연시간,공연시작일자,공연종료일자,...,공연기간,휴일,시간대,좌석등급개수,확진자변화율,강수,기온,습도,미세먼지등급,초미세먼지등급
0,0,1101064,FC222055,FC222055-02,PF300001,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-26,2022-06-30,...,66,평일,밤,2,184.694520,0.0,13.200000,31.0,1.0,1.0
1,91,1101064,FC223420,FC223420-02,PF300003,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-19,2022-04-30,...,12,평일,밤,1,184.694520,0.0,13.200000,31.0,1.0,1.0
2,723,1101064,FC223671,FC223671-01,PF300257,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-22,2022-07-16,...,86,평일,밤,2,184.694520,0.0,13.200000,31.0,1.0,1.0
3,2134,1101064,FC223740,FC223740-02,PF300778,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-01,2022-04-30,...,30,평일,밤,1,184.694520,0.0,13.200000,31.0,1.0,1.0
4,2919,1101064,FC223740,FC223740-03,PF301247,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-26,2022-06-18,...,54,평일,밤,1,184.694520,0.0,13.200000,31.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196762,196748,1118052,FC223787,FC223787-01,PF427890,2021-06-20 12:00:00,2021-06-20,12:00,2021-05-01,2021-06-26,...,57,주말,낮,1,-16.243655,0.0,21.200001,90.0,1.0,2.0
196763,196750,1118052,FC223787,FC223787-01,PF427890,2021-06-26 12:00:00,2021-06-26,12:00,2021-05-01,2021-06-26,...,57,주말,낮,1,-2.230483,0.0,23.400000,82.0,0.0,1.0
196764,196751,1118052,FC223787,FC223787-01,PF427890,2021-06-26 14:00:00,2021-06-26,14:00,2021-05-01,2021-06-26,...,57,주말,낮,1,-2.230483,0.0,22.100000,84.0,0.0,1.0
196765,196752,1118052,FC223787,FC223787-01,PF427890,2021-06-26 16:00:00,2021-06-26,16:00,2021-05-01,2021-06-26,...,57,주말,낮,1,-2.230483,0.0,21.799999,86.0,0.0,1.0
196766,196757,1105059,FC222232,FC222232-01,PF433731,2022-11-13 18:00:00,2022-11-13,18:00,2022-11-13,2022-11-13,...,1,주말,밤,1,-14.516427,0.0,9.500000,84.0,0.0,0.0

In [ ]:
all_covid_weather.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO+date+dong+sale+tropy+time+level+covid+weather.csv', index=False)

## allCO_230816_sale_update (미세먼지 수정함)

In [ ]:
allCO = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO_230816_sale_update.csv')
allCO = allCO.drop(['미세먼지등급','초미세먼지등급'], axis = 1)

<ipython-input-88-886af04b13e9>:1: DtypeWarning: Columns (14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  allCO = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO_230816_sale_update.csv')

In [ ]:
weather = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/Outsource/Weather/final_weather_seoul.csv')

In [ ]:
from datetime import datetime
allCO['공연정각'] = allCO['공연시간'].apply(lambda x: datetime.strptime(x, '%H:%M').replace(minute=0).strftime('%H:%M'))
weather.rename(columns={'date': '공연일','time':'공연정각'}, inplace=True)

In [ ]:
allCO

,행정동코드,공연시설코드,공연장코드,공연코드,공연일시,공연일,공연시간,공연시작일자,공연종료일자,소요시간,...,수상실적개수,공연기간,휴일,시간대,좌석등급개수,확진자변화율,강수,기온,습도,공연정각
0,1101064,FC222055,FC222055-02,PF300001,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-26,2022-06-30,105.0,...,0,66,평일,밤,2,184.694520,0.0,13.200000,31.0,20:00
1,1101064,FC222055,FC222055-02,PF300001,2022-04-27 20:00:00,2022-04-27,20:00,2022-04-26,2022-06-30,105.0,...,0,66,평일,밤,2,-15.066372,0.0,11.700000,54.0,20:00
2,1101064,FC222055,FC222055-02,PF300001,2022-04-28 20:00:00,2022-04-28,20:00,2022-04-26,2022-06-30,105.0,...,0,66,평일,밤,2,-20.908223,2.5,10.800000,95.0,20:00
3,1101064,FC222055,FC222055-02,PF300001,2022-04-29 20:00:00,2022-04-29,20:00,2022-04-26,2022-06-30,105.0,...,0,66,평일,밤,2,-15.182786,0.0,11.000000,70.0,20:00
4,1101064,FC222055,FC222055-02,PF300001,2022-04-30 15:00:00,2022-04-30,15:00,2022-04-26,2022-06-30,105.0,...,0,66,주말,낮,2,-16.450945,0.0,10.100000,65.0,15:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196762,1103071,FC223333,FC223333-01,PF427814,2021-10-03 19:00:00,2021-10-03,19:00,2021-09-24,2021-10-03,NaN,...,0,10,공휴일,밤,1,-7.187894,0.0,21.000000,70.0,19:00
196763,1103071,FC223333,FC223333-01,PF427814,2021-10-03 19:30:00,2021-10-03,19:30,2021-09-24,2021-10-03,NaN,...,0,10,공휴일,밤,1,-7.187894,0.0,21.000000,70.0,19:00
196764,1103071,FC223333,FC223333-01,PF427814,2021-10-03 20:00:00,2021-10-03,20:00,2021-09-24,2021-10-03,NaN,...,0,10,공휴일,밤,1,-7.187894,0.0,21.299999,67.0,20:00
196765,1103071,FC223333,FC223333-01,PF427814,2021-10-03 20:30:00,2021-10-03,20:30,2021-09-24,2021-10-03,NaN,...,0,10,공휴일,밤,1,-7.187894,0.0,21.299999,67.0,20:00
196766,1103071,FC223333,FC223333-01,PF427814,2021-10-03 21:00:00,2021-10-03,21:00,2021-09-24,2021-10-03,NaN,...,0,10,공휴일,밤,1,-7.187894,0.0,21.500000,68.0,21:00

In [ ]:
weather

           행정동코드         공연일   공연정각  강수      기온  습도  미세먼지등급  초미세먼지등급
0        1123071  2019-07-01  00:00    0.0  25.900000   66.0     1.0      1.0
1        1123071  2019-07-01  01:00    0.0  26.700001   59.0     1.0      2.0
2        1123071  2019-07-01  02:00    0.0  27.400000   58.0     1.0      2.0
3        1123071  2019-07-01  03:00    0.0  28.000000   52.0     1.0      1.0
4        1123071  2019-07-01  04:00    0.0  28.900000   48.0     1.0      1.0
...          ...         ...    ...    ...        ...    ...     ...      ...
5375995  1107054  2022-12-31  19:00    0.0   1.800000   46.0     1.0      2.0
5375996  1107054  2022-12-31  20:00    0.0   0.900000   49.0     1.0      2.0
5375997  1107054  2022-12-31  21:00    0.0  -0.400000   58.0     1.0      2.0
5375998  1107054  2022-12-31  22:00    0.0   0.000000   56.0     1.0      2.0
5375999  1107054  2022-12-31  23:00    0.0   0.400000   57.0     1.0      2.0

[5376000 rows x 8 columns]

In [ ]:
all_covid_weather = pd.merge(allCO, weather[['행정동코드','공연일','공연정각','미세먼지등급','초미세먼지등급']], on=['행정동코드','공연일','공연정각'],how="inner")
all_covid_weather = all_covid_weather.drop(['공연정각'], axis = 1)

In [ ]:
all_covid_weather

,행정동코드,공연시설코드,공연장코드,공연코드,공연일시,공연일,공연시간,공연시작일자,공연종료일자,소요시간,...,공연기간,휴일,시간대,좌석등급개수,확진자변화율,강수,기온,습도,미세먼지등급,초미세먼지등급
0,1101064,FC222055,FC222055-02,PF300001,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-26,2022-06-30,105.0,...,66,평일,밤,2,184.694520,0.0,13.200000,31.0,1.0,1.0
1,1101064,FC223420,FC223420-02,PF300003,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-19,2022-04-30,60.0,...,12,평일,밤,1,184.694520,0.0,13.200000,31.0,1.0,1.0
2,1101064,FC223671,FC223671-01,PF300257,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-22,2022-07-16,100.0,...,86,평일,밤,2,184.694520,0.0,13.200000,31.0,1.0,1.0
3,1101064,FC223740,FC223740-02,PF300778,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-01,2022-04-30,100.0,...,30,평일,밤,1,184.694520,0.0,13.200000,31.0,1.0,1.0
4,1101064,FC223740,FC223740-03,PF301247,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-26,2022-06-18,100.0,...,54,평일,밤,1,184.694520,0.0,13.200000,31.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196762,1103071,FC223333,FC223333-01,PF427814,2021-10-03 19:00:00,2021-10-03,19:00,2021-09-24,2021-10-03,NaN,...,10,공휴일,밤,1,-7.187894,0.0,21.000000,70.0,1.0,1.0
196763,1103071,FC223333,FC223333-01,PF427814,2021-10-03 19:30:00,2021-10-03,19:30,2021-09-24,2021-10-03,NaN,...,10,공휴일,밤,1,-7.187894,0.0,21.000000,70.0,1.0,1.0
196764,1103071,FC223333,FC223333-01,PF427814,2021-10-03 20:00:00,2021-10-03,20:00,2021-09-24,2021-10-03,NaN,...,10,공휴일,밤,1,-7.187894,0.0,21.299999,67.0,1.0,1.0
196765,1103071,FC223333,FC223333-01,PF427814,2021-10-03 20:30:00,2021-10-03,20:30,2021-09-24,2021-10-03,NaN,...,10,공휴일,밤,1,-7.187894,0.0,21.299999,67.0,1.0,1.0
196766,1103071,FC223333,FC223333-01,PF427814,2021-10-03 21:00:00,2021-10-03,21:00,2021-09-24,2021-10-03,NaN,...,10,공휴일,밤,1,-7.187894,0.0,21.500000,68.0,1.0,1.0

In [ ]:
all_covid_weather.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO_230816_sale_update.csv', index=False)

# COCO_clust: 평일/주말/공휴일의 하루 평균 공연 횟수

In [ ]:
CO = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO+date+dong+sale+tropy+time+level+covid+weather.csv',usecols=['공연시설코드','공연장코드','공연코드','공연일','공연시간','휴일','시간대','공연기간','좌석등급개수'])
CO

,공연시설코드,공연장코드,공연코드,공연일,공연시간,공연기간,휴일,시간대,좌석등급개수
0,FC222055,FC222055-02,PF300001,2022-04-26,20:00,66,평일,밤,2
1,FC223420,FC223420-02,PF300003,2022-04-26,20:00,12,평일,밤,1
2,FC223671,FC223671-01,PF300257,2022-04-26,20:00,86,평일,밤,2
3,FC223740,FC223740-02,PF300778,2022-04-26,20:00,30,평일,밤,1
4,FC223740,FC223740-03,PF301247,2022-04-26,20:00,54,평일,밤,1
...,...,...,...,...,...,...,...,...,...
196762,FC223787,FC223787-01,PF427890,2021-06-20,12:00,57,주말,낮,1
196763,FC223787,FC223787-01,PF427890,2021-06-26,12:00,57,주말,낮,1
196764,FC223787,FC223787-01,PF427890,2021-06-26,14:00,57,주말,낮,1
196765,FC223787,FC223787-01,PF427890,2021-06-26,16:00,57,주말,낮,1
196766,FC222232,FC222232-01,PF433731,2022-11-13,18:00,1,주말,밤,1

In [ ]:
CO[(CO['공연코드'] == 'PF424187')]

,공연시설코드,공연장코드,공연코드,공연일,공연시간,공연기간,휴일,시간대,좌석등급개수
195614,FC222005,FC222005-03,PF424187,2022-12-17,14:00,31,주말,낮,2
195616,FC222005,FC222005-03,PF424187,2022-12-24,20:00,31,주말,밤,2

In [ ]:
CO[(CO['공연코드'] == 'PF427814') & (CO['공연일'] == '2021-10-03')]

,공연시설코드,공연장코드,공연코드,공연일,공연시간,공연기간,휴일,시간대,좌석등급개수
196725,FC223333,FC223333-01,PF427814,2021-10-03,10:30,10,공휴일,아침,1
196726,FC223333,FC223333-01,PF427814,2021-10-03,11:00,10,공휴일,아침,1
196727,FC223333,FC223333-01,PF427814,2021-10-03,11:30,10,공휴일,아침,1
196728,FC223333,FC223333-01,PF427814,2021-10-03,12:00,10,공휴일,낮,1
196729,FC223333,FC223333-01,PF427814,2021-10-03,12:30,10,공휴일,낮,1
196730,FC223333,FC223333-01,PF427814,2021-10-03,13:00,10,공휴일,낮,1
196731,FC223333,FC223333-01,PF427814,2021-10-03,13:30,10,공휴일,낮,1
196732,FC223333,FC223333-01,PF427814,2021-10-03,14:00,10,공휴일,낮,1
196733,FC223333,FC223333-01,PF427814,2021-10-03,14:30,10,공휴일,낮,1
196734,FC223333,FC223333-01,PF427814,2021-10-03,15:00,10,공휴일,낮,1
196735,FC223333,FC223333-01,PF427814,2021-10-03,15:30,10,공휴일,낮,1
196736,FC223333,FC223333-01,PF427814,2021-10-03,16:00,10,공휴일,낮,1
196737,FC223333,FC223333-01,PF427814,2021-10-03,16:30,10,공휴일,낮,1
196738,FC223333,FC223333-01,PF427814,2021-10-03,17:00,10,공휴일,낮,1
196739,FC223333,FC223333-01,PF427814,2021-10-03,17:30,10,공휴일,낮,1
196740,FC223333,FC223333-01,PF427814,2021-10-03,18:00,10,공휴일,밤,1
196741,FC223333,FC223333-01,PF427814,2021-10-03,18:30,10,공휴일,밤,1
196742,FC223333,FC223333-01,PF427814,2021-10-03,19:00,10,공휴일,밤,1
196743,FC223333,FC223333-01,PF427814,2021-10-03,19:30,10,공휴일,밤,1
196744,FC223333,FC223333-01,PF427814,2021-10-03,20:00,10,공휴일,밤,1
196745,FC223333,FC223333-01,PF427814,2021-10-03,20:30,10,공휴일,밤,1
196746,FC223333,FC223333-01,PF427814,2021-10-03,21:00,10,공휴일,밤,1

In [ ]:
CO['시간대횟차'] = CO.groupby(['공연코드', '공연일', '휴일', '시간대'])['공연시간'].transform('nunique')
CO['하루횟차'] = CO.groupby(['공연코드', '공연일'])['공연시간'].transform('nunique')
CO

,공연시설코드,공연장코드,공연코드,공연일,공연시간,공연기간,휴일,시간대,좌석등급개수,시간대횟차,하루횟차
0,FC222055,FC222055-02,PF300001,2022-04-26,20:00,66,평일,밤,2,1,1
1,FC223420,FC223420-02,PF300003,2022-04-26,20:00,12,평일,밤,1,1,1
2,FC223671,FC223671-01,PF300257,2022-04-26,20:00,86,평일,밤,2,1,1
3,FC223740,FC223740-02,PF300778,2022-04-26,20:00,30,평일,밤,1,1,1
4,FC223740,FC223740-03,PF301247,2022-04-26,20:00,54,평일,밤,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
196762,FC223787,FC223787-01,PF427890,2021-06-20,12:00,57,주말,낮,1,2,2
196763,FC223787,FC223787-01,PF427890,2021-06-26,12:00,57,주말,낮,1,3,3
196764,FC223787,FC223787-01,PF427890,2021-06-26,14:00,57,주말,낮,1,3,3
196765,FC223787,FC223787-01,PF427890,2021-06-26,16:00,57,주말,낮,1,3,3
196766,FC222232,FC222232-01,PF433731,2022-11-13,18:00,1,주말,밤,1,1,2

In [ ]:
CO[(CO['공연코드'] == 'PF427814') & (CO['공연일'] == '2021-10-03')]

,공연시설코드,공연장코드,공연코드,공연일,공연시간,공연기간,휴일,시간대,좌석등급개수,시간대횟차,하루횟차
196725,FC223333,FC223333-01,PF427814,2021-10-03,10:30,10,공휴일,아침,1,3,22
196726,FC223333,FC223333-01,PF427814,2021-10-03,11:00,10,공휴일,아침,1,3,22
196727,FC223333,FC223333-01,PF427814,2021-10-03,11:30,10,공휴일,아침,1,3,22
196728,FC223333,FC223333-01,PF427814,2021-10-03,12:00,10,공휴일,낮,1,12,22
196729,FC223333,FC223333-01,PF427814,2021-10-03,12:30,10,공휴일,낮,1,12,22
196730,FC223333,FC223333-01,PF427814,2021-10-03,13:00,10,공휴일,낮,1,12,22
196731,FC223333,FC223333-01,PF427814,2021-10-03,13:30,10,공휴일,낮,1,12,22
196732,FC223333,FC223333-01,PF427814,2021-10-03,14:00,10,공휴일,낮,1,12,22
196733,FC223333,FC223333-01,PF427814,2021-10-03,14:30,10,공휴일,낮,1,12,22
196734,FC223333,FC223333-01,PF427814,2021-10-03,15:00,10,공휴일,낮,1,12,22
196735,FC223333,FC223333-01,PF427814,2021-10-03,15:30,10,공휴일,낮,1,12,22
196736,FC223333,FC223333-01,PF427814,2021-10-03,16:00,10,공휴일,낮,1,12,22
196737,FC223333,FC223333-01,PF427814,2021-10-03,16:30,10,공휴일,낮,1,12,22
196738,FC223333,FC223333-01,PF427814,2021-10-03,17:00,10,공휴일,낮,1,12,22
196739,FC223333,FC223333-01,PF427814,2021-10-03,17:30,10,공휴일,낮,1,12,22
196740,FC223333,FC223333-01,PF427814,2021-10-03,18:00,10,공휴일,밤,1,7,22
196741,FC223333,FC223333-01,PF427814,2021-10-03,18:30,10,공휴일,밤,1,7,22
196742,FC223333,FC223333-01,PF427814,2021-10-03,19:00,10,공휴일,밤,1,7,22
196743,FC223333,FC223333-01,PF427814,2021-10-03,19:30,10,공휴일,밤,1,7,22
196744,FC223333,FC223333-01,PF427814,2021-10-03,20:00,10,공휴일,밤,1,7,22
196745,FC223333,FC223333-01,PF427814,2021-10-03,20:30,10,공휴일,밤,1,7,22
196746,FC223333,FC223333-01,PF427814,2021-10-03,21:00,10,공휴일,밤,1,7,22

In [ ]:
CO = CO.drop(['공연시간'], axis = 1)
CO = CO.drop_duplicates()
CO

,공연시설코드,공연장코드,공연코드,공연일,공연기간,휴일,시간대,좌석등급개수,시간대횟차,하루횟차
0,FC222055,FC222055-02,PF300001,2022-04-26,66,평일,밤,2,1,1
1,FC223420,FC223420-02,PF300003,2022-04-26,12,평일,밤,1,1,1
2,FC223671,FC223671-01,PF300257,2022-04-26,86,평일,밤,2,1,1
3,FC223740,FC223740-02,PF300778,2022-04-26,30,평일,밤,1,1,1
4,FC223740,FC223740-03,PF301247,2022-04-26,54,평일,밤,1,1,1
...,...,...,...,...,...,...,...,...,...,...
196755,FC223787,FC223787-01,PF427890,2021-05-22,57,주말,낮,1,1,1
196756,FC223787,FC223787-01,PF427890,2021-05-30,57,주말,낮,1,2,2
196759,FC223787,FC223787-01,PF427890,2021-06-06,57,공휴일,낮,1,2,2
196763,FC223787,FC223787-01,PF427890,2021-06-26,57,주말,낮,1,3,3
196766,FC222232,FC222232-01,PF433731,2022-11-13,1,주말,밤,1,1,2

In [ ]:
CO[(CO['공연코드'] == 'PF427814') & (CO['공연일'] == '2021-10-03')]

,공연시설코드,공연장코드,공연코드,공연일,공연기간,휴일,시간대,좌석등급개수,시간대횟차,하루횟차
196725,FC223333,FC223333-01,PF427814,2021-10-03,10,공휴일,아침,1,3,22
196728,FC223333,FC223333-01,PF427814,2021-10-03,10,공휴일,낮,1,12,22
196740,FC223333,FC223333-01,PF427814,2021-10-03,10,공휴일,밤,1,7,22

In [ ]:
CO[CO['휴일'] == '공휴일']

,공연시설코드,공연장코드,공연코드,공연일,공연기간,휴일,시간대,좌석등급개수,시간대횟차,하루횟차
212,FC222055,FC222055-02,PF300001,2022-05-05,66,공휴일,밤,2,1,1
213,FC223671,FC223671-01,PF300257,2022-05-05,86,공휴일,밤,2,1,2
214,FC224042,FC224042-01,PF300475,2022-05-05,31,공휴일,밤,1,1,2
215,FC223591,FC223591-01,PF300670,2022-05-05,420,공휴일,밤,1,1,2
216,FC223455,FC223455-02,PF302320,2022-05-05,696,공휴일,밤,2,1,2
...,...,...,...,...,...,...,...,...,...,...
196728,FC223333,FC223333-01,PF427814,2021-10-03,10,공휴일,낮,1,12,22
196740,FC223333,FC223333-01,PF427814,2021-10-03,10,공휴일,밤,1,7,22
196747,FC223787,FC223787-01,PF427890,2021-05-05,57,공휴일,낮,1,3,3
196753,FC223787,FC223787-01,PF427890,2021-05-19,57,공휴일,낮,1,2,2
196759,FC223787,FC223787-01,PF427890,2021-06-06,57,공휴일,낮,1,2,2

In [ ]:
CO_uni = CO.drop(['시간대','시간대횟차'], axis = 1)
CO_uni = CO_uni.drop_duplicates()
CO_uni

          공연시설코드        공연장코드      공연코드         공연일  공연기간   휴일  좌석등급개수  하루횟차
0       FC222055  FC222055-02  PF300001  2022-04-26    66   평일       2     1
1       FC223420  FC223420-02  PF300003  2022-04-26    12   평일       1     1
2       FC223671  FC223671-01  PF300257  2022-04-26    86   평일       2     1
3       FC223740  FC223740-02  PF300778  2022-04-26    30   평일       1     1
4       FC223740  FC223740-03  PF301247  2022-04-26    54   평일       1     1
...          ...          ...       ...         ...   ...  ...     ...   ...
196753  FC223787  FC223787-01  PF427890  2021-05-19    57  공휴일       1     2
196755  FC223787  FC223787-01  PF427890  2021-05-22    57   주말       1     1
196756  FC223787  FC223787-01  PF427890  2021-05-30    57   주말       1     2
196759  FC223787  FC223787-01  PF427890  2021-06-06    57  공휴일       1     2
196763  FC223787  FC223787-01  PF427890  2021-06-26    57   주말       1     3

[132186 rows x 8 columns]

In [ ]:
CO_uni[(CO_uni['공연코드'] == 'PF427814') & (CO_uni['공연일'] == '2021-10-03')]

          공연시설코드        공연장코드      공연코드         공연일  공연기간   휴일  좌석등급개수  하루횟차
196725  FC223333  FC223333-01  PF427814  2021-10-03    10  공휴일       1    22

In [ ]:
for index, row in CO_uni.iterrows():
    if row['휴일'] == '주말':
        CO_uni.at[index, '주말'] = row['하루횟차']
    elif row['휴일'] == '평일':
        CO_uni.at[index, '평일'] = row['하루횟차']
    elif row['휴일'] == '공휴일':
        CO_uni.at[index, '공휴일'] = row['하루횟차']

# '하루횟차' 열 삭제
CO_uni_day = CO_uni.drop(columns='하루횟차')
CO_uni_day

,공연시설코드,공연장코드,공연코드,공연일,공연기간,휴일,좌석등급개수,평일,주말,공휴일
0,FC222055,FC222055-02,PF300001,2022-04-26,66,평일,2,1.0,NaN,NaN
1,FC223420,FC223420-02,PF300003,2022-04-26,12,평일,1,1.0,NaN,NaN
2,FC223671,FC223671-01,PF300257,2022-04-26,86,평일,2,1.0,NaN,NaN
3,FC223740,FC223740-02,PF300778,2022-04-26,30,평일,1,1.0,NaN,NaN
4,FC223740,FC223740-03,PF301247,2022-04-26,54,평일,1,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
196753,FC223787,FC223787-01,PF427890,2021-05-19,57,공휴일,1,NaN,NaN,2.0
196755,FC223787,FC223787-01,PF427890,2021-05-22,57,주말,1,NaN,1.0,NaN
196756,FC223787,FC223787-01,PF427890,2021-05-30,57,주말,1,NaN,2.0,NaN
196759,FC223787,FC223787-01,PF427890,2021-06-06,57,공휴일,1,NaN,NaN,2.0
196763,FC223787,FC223787-01,PF427890,2021-06-26,57,주말,1,NaN,3.0,NaN

In [ ]:
CO_uni_day[(CO_uni_day['공연코드'] == 'PF427814')]

,공연시설코드,공연장코드,공연코드,공연일,공연기간,휴일,좌석등급개수,평일,주말,공휴일
196579,FC223333,FC223333-01,PF427814,2021-09-24,10,평일,1,16.0,NaN,NaN
196595,FC223333,FC223333-01,PF427814,2021-09-25,10,주말,1,NaN,22.0,NaN
196617,FC223333,FC223333-01,PF427814,2021-09-26,10,주말,1,NaN,22.0,NaN
196639,FC223333,FC223333-01,PF427814,2021-09-27,10,평일,1,16.0,NaN,NaN
196655,FC223333,FC223333-01,PF427814,2021-09-29,10,평일,1,16.0,NaN,NaN
196671,FC223333,FC223333-01,PF427814,2021-09-30,10,평일,1,16.0,NaN,NaN
196687,FC223333,FC223333-01,PF427814,2021-10-01,10,평일,1,16.0,NaN,NaN
196703,FC223333,FC223333-01,PF427814,2021-10-02,10,주말,1,NaN,22.0,NaN
196725,FC223333,FC223333-01,PF427814,2021-10-03,10,공휴일,1,NaN,NaN,22.0

In [ ]:
CO_uni_uni = CO_uni_day.drop(columns=['공연일','휴일'])
CO_uni_uni = CO_uni_uni.drop_duplicates()
CO_uni_uni

          공연시설코드        공연장코드      공연코드  공연기간  좌석등급개수    평일    주말   공휴일
0       FC222055  FC222055-02  PF300001    66       2   1.0   NaN   NaN
1       FC223420  FC223420-02  PF300003    12       1   1.0   NaN   NaN
2       FC223671  FC223671-01  PF300257    86       2   1.0   NaN   NaN
3       FC223740  FC223740-02  PF300778    30       1   1.0   NaN   NaN
4       FC223740  FC223740-03  PF301247    54       1   1.0   NaN   NaN
...          ...          ...       ...   ...     ...   ...   ...   ...
196579  FC223333  FC223333-01  PF427814    10       1  16.0   NaN   NaN
196595  FC223333  FC223333-01  PF427814    10       1   NaN  22.0   NaN
196725  FC223333  FC223333-01  PF427814    10       1   NaN   NaN  22.0
196747  FC223787  FC223787-01  PF427890    57       1   NaN   NaN   3.0
196753  FC223787  FC223787-01  PF427890    57       1   NaN   NaN   2.0

[31973 rows x 8 columns]

In [ ]:
CO_uni_uni[CO_uni_uni['공연코드'] == 'PF427814']

          공연시설코드        공연장코드      공연코드  공연기간  좌석등급개수    평일    주말   공휴일
196579  FC223333  FC223333-01  PF427814    10       1  16.0   NaN   NaN
196595  FC223333  FC223333-01  PF427814    10       1   NaN  22.0   NaN
196725  FC223333  FC223333-01  PF427814    10       1   NaN   NaN  22.0

In [ ]:
grouped = CO_uni_uni.groupby(['공연시설코드', '공연장코드', '공연코드', '공연기간', '좌석등급개수']).agg(
    평일평균횟수=pd.NamedAgg(column='평일', aggfunc='mean'),
    주말평균횟수=pd.NamedAgg(column='주말', aggfunc='mean'),
    공휴일평균횟수=pd.NamedAgg(column='공휴일', aggfunc='mean')
).reset_index()

grouped

         공연시설코드        공연장코드      공연코드  공연기간  좌석등급개수  평일평균횟수  주말평균횟수  공휴일평균횟수
0      FC222005  FC222005-02  PF374942     2       2     2.0     2.0      NaN
1      FC222005  FC222005-03  PF351529   965       2     1.5     1.5      1.0
2      FC222005  FC222005-03  PF424187    31       2     NaN     1.0      NaN
3      FC222005  FC222005-04  PF361283  1857       3     1.5     1.5      1.5
4      FC222005  FC222005-04  PF422043    12       1     1.0     2.0      NaN
...         ...          ...       ...   ...     ...     ...     ...      ...
21298  FC225489  FC225489-01  PF310442     1       2     NaN     1.0      NaN
21299  FC225489  FC225489-01  PF310552    29       1     1.0     1.0      NaN
21300  FC225489  FC225489-01  PF316039    36       1     1.0     NaN      NaN
21301  FC225489  FC225489-01  PF424689    29       1     1.0     NaN      NaN
21302  FC225541  FC225541-01  PF426902     1       1     1.0     NaN      NaN

[21303 rows x 8 columns]

In [ ]:
grouped[["평일평균횟수", "주말평균횟수", "공휴일평균횟수"]] = grouped[["평일평균횟수", "주말평균횟수", "공휴일평균횟수"]].fillna(0)
grouped

         공연시설코드        공연장코드      공연코드  공연기간  좌석등급개수  평일평균횟수  주말평균횟수  공휴일평균횟수
0      FC222005  FC222005-02  PF374942     2       2     2.0     2.0      0.0
1      FC222005  FC222005-03  PF351529   965       2     1.5     1.5      1.0
2      FC222005  FC222005-03  PF424187    31       2     0.0     1.0      0.0
3      FC222005  FC222005-04  PF361283  1857       3     1.5     1.5      1.5
4      FC222005  FC222005-04  PF422043    12       1     1.0     2.0      0.0
...         ...          ...       ...   ...     ...     ...     ...      ...
21298  FC225489  FC225489-01  PF310442     1       2     0.0     1.0      0.0
21299  FC225489  FC225489-01  PF310552    29       1     1.0     1.0      0.0
21300  FC225489  FC225489-01  PF316039    36       1     1.0     0.0      0.0
21301  FC225489  FC225489-01  PF424689    29       1     1.0     0.0      0.0
21302  FC225541  FC225541-01  PF426902     1       1     1.0     0.0      0.0

[21303 rows x 8 columns]

In [ ]:
grouped[grouped['공연코드'] == 'PF427814']

         공연시설코드        공연장코드      공연코드  공연기간  좌석등급개수    평일    주말   공휴일
11392  FC223333  FC223333-01  PF427814    10       1  16.0  22.0  22.0

In [ ]:
grouped.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/coco_day_count.csv')

In [ ]:
coco_day_count = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/coco_day_count.csv')
coco_day_count

,Unnamed: 0,공연시설코드,공연장코드,공연코드,공연기간,좌석등급개수,평일평균횟수,주말평균횟수,공휴일평균횟수
0,0,FC222005,FC222005-02,PF374942,2,2,2.0,2.0,0.0
1,1,FC222005,FC222005-03,PF351529,965,2,1.5,1.5,1.0
2,2,FC222005,FC222005-03,PF424187,31,2,0.0,1.0,0.0
3,3,FC222005,FC222005-04,PF361283,1857,3,1.5,1.5,1.5
4,4,FC222005,FC222005-04,PF422043,12,1,1.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...
21298,21298,FC225489,FC225489-01,PF310442,1,2,0.0,1.0,0.0
21299,21299,FC225489,FC225489-01,PF310552,29,1,1.0,1.0,0.0
21300,21300,FC225489,FC225489-01,PF316039,36,1,1.0,0.0,0.0
21301,21301,FC225489,FC225489-01,PF424689,29,1,1.0,0.0,0.0
21302,21302,FC225541,FC225541-01,PF426902,1,1,1.0,0.0,0.0

In [ ]:
coco = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/coco_clust.csv')
coco

,공연시설코드,공연장코드,공연코드,공연횟수,좌석수,사전예매건수,사전취소건수,당일예매건수,당일취소건수,전체예매건수,...,예매/취소금액,할인금액,장당금액,평균할인율,총매출액,편의시설,장애인시설,주차시설,교통개수,무대시설
0,FC222005,FC222005-02,PF374942,4,318.0,27,12,0,0,27,...,84170.370370,1866.666667,85159.259259,2.191971,2272600,2,0,1,28,2
1,FC222005,FC222005-03,PF351529,154,333.0,879,176,136,0,1015,...,25362.955665,6743.842365,26269.359606,25.671895,25743400,2,0,1,28,2
2,FC222005,FC222005-03,PF424187,2,333.0,34,7,0,0,34,...,32352.941176,0.000000,32352.941176,0.000000,1100000,2,0,1,28,2
3,FC222005,FC222005-04,PF361283,258,334.0,4194,1223,348,18,4542,...,33523.227653,1361.734919,34703.324527,3.923932,152262500,2,0,1,28,2
4,FC222005,FC222005-04,PF422043,14,334.0,65,25,0,0,65,...,39692.307692,0.000000,39692.307692,0.000000,2580000,2,0,1,28,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20508,FC225489,FC225489-01,PF310442,1,128.0,66,4,0,0,66,...,13484.848485,0.000000,13484.848485,0.000000,890000,0,0,0,49,1
20509,FC225489,FC225489-01,PF310552,3,128.0,34,5,10,0,44,...,7272.727273,2727.272727,10000.000000,27.272727,320000,0,0,0,49,1
20510,FC225489,FC225489-01,PF316039,2,128.0,12,1,1,0,13,...,0.000000,0.000000,0.000000,0.000000,0,0,0,0,49,1
20511,FC225489,FC225489-01,PF424689,2,128.0,9,4,4,0,13,...,6923.076923,3076.923077,10000.000000,30.769231,90000,0,0,0,49,1
20512,FC225541,FC225541-01,PF426902,1,171.0,0,0,167,0,167,...,0.000000,0.000000,0.000000,0.000000,0,0,3,1,49,1

In [ ]:
merged_df = pd.merge(coco, grouped,on=['공연시설코드','공연장코드','공연코드'])
merged_df

,공연시설코드,공연장코드,공연코드,공연횟수,좌석수,사전예매건수,사전취소건수,당일예매건수,당일취소건수,전체예매건수,...,편의시설,장애인시설,주차시설,교통개수,무대시설,공연기간,좌석등급개수,평일평균횟수,주말평균횟수,공휴일평균횟수
0,FC222005,FC222005-02,PF374942,4,318.0,27,12,0,0,27,...,2,0,1,28,2,2,2,2.0,2.0,0.0
1,FC222005,FC222005-03,PF351529,154,333.0,879,176,136,0,1015,...,2,0,1,28,2,965,2,1.5,1.5,1.0
2,FC222005,FC222005-03,PF424187,2,333.0,34,7,0,0,34,...,2,0,1,28,2,31,2,0.0,1.0,0.0
3,FC222005,FC222005-04,PF361283,258,334.0,4194,1223,348,18,4542,...,2,0,1,28,2,1857,3,1.5,1.5,1.5
4,FC222005,FC222005-04,PF422043,14,334.0,65,25,0,0,65,...,2,0,1,28,2,12,1,1.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20508,FC225489,FC225489-01,PF310442,1,128.0,66,4,0,0,66,...,0,0,0,49,1,1,2,0.0,1.0,0.0
20509,FC225489,FC225489-01,PF310552,3,128.0,34,5,10,0,44,...,0,0,0,49,1,29,1,1.0,1.0,0.0
20510,FC225489,FC225489-01,PF316039,2,128.0,12,1,1,0,13,...,0,0,0,49,1,36,1,1.0,0.0,0.0
20511,FC225489,FC225489-01,PF424689,2,128.0,9,4,4,0,13,...,0,0,0,49,1,29,1,1.0,0.0,0.0
20512,FC225541,FC225541-01,PF426902,1,171.0,0,0,167,0,167,...,0,3,1,49,1,1,1,1.0,0.0,0.0

In [ ]:
merged_df[merged_df['공연코드'] == 'PF427814']

,공연시설코드,공연장코드,공연코드,공연횟수,좌석수,사전예매건수,사전취소건수,당일예매건수,당일취소건수,전체예매건수,...,편의시설,장애인시설,주차시설,교통개수,무대시설,공연기간,좌석등급개수,평일평균횟수,주말평균횟수,공휴일평균횟수
11261,FC223333,FC223333-01,PF427814,168,182.0,233,70,3,1,236,...,1,0,1,29,2,10,1,16.0,22.0,22.0

In [ ]:
merged_df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/coco_clust(815).csv', index=False)

# COCO_clust: 평일+주말+공휴일 = 총횟수

In [ ]:
CO = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO_230816_sale_update.csv',usecols=['공연시설코드','공연장코드','공연코드','공연일','공연시간','휴일','시간대'])
CO

          공연시설코드        공연장코드      공연코드         공연일   공연시간   휴일 시간대
0       FC222055  FC222055-02  PF300001  2022-04-26  20:00   평일   밤
1       FC222055  FC222055-02  PF300001  2022-04-27  20:00   평일   밤
2       FC222055  FC222055-02  PF300001  2022-04-28  20:00   평일   밤
3       FC222055  FC222055-02  PF300001  2022-04-29  20:00   평일   밤
4       FC222055  FC222055-02  PF300001  2022-04-30  15:00   주말   낮
...          ...          ...       ...         ...    ...  ...  ..
196762  FC223333  FC223333-01  PF427814  2021-10-03  19:00  공휴일   밤
196763  FC223333  FC223333-01  PF427814  2021-10-03  19:30  공휴일   밤
196764  FC223333  FC223333-01  PF427814  2021-10-03  20:00  공휴일   밤
196765  FC223333  FC223333-01  PF427814  2021-10-03  20:30  공휴일   밤
196766  FC223333  FC223333-01  PF427814  2021-10-03  21:00  공휴일   밤

[196767 rows x 7 columns]

In [ ]:
CO['공연총횟수'] = CO.groupby('공연코드')['공연코드'].transform('count')
CO['평일총횟수'] = CO.groupby('공연코드')['휴일'].transform(lambda x: (x == '평일').sum())
CO['주말총횟수'] = CO.groupby('공연코드')['휴일'].transform(lambda x: (x == '주말').sum())
CO['공휴일총횟수'] = CO.groupby('공연코드')['휴일'].transform(lambda x: (x == '공휴일').sum())
CO

,공연시설코드,공연장코드,공연코드,공연일,공연시간,휴일,시간대,공연총횟수,평일총횟수,주말총횟수,공휴일총횟수
0,FC222055,FC222055-02,PF300001,2022-04-26,20:00,평일,밤,84,43,34,7
1,FC222055,FC222055-02,PF300001,2022-04-27,20:00,평일,밤,84,43,34,7
2,FC222055,FC222055-02,PF300001,2022-04-28,20:00,평일,밤,84,43,34,7
3,FC222055,FC222055-02,PF300001,2022-04-29,20:00,평일,밤,84,43,34,7
4,FC222055,FC222055-02,PF300001,2022-04-30,15:00,주말,낮,84,43,34,7
...,...,...,...,...,...,...,...,...,...,...,...
196762,FC223333,FC223333-01,PF427814,2021-10-03,19:00,공휴일,밤,168,80,66,22
196763,FC223333,FC223333-01,PF427814,2021-10-03,19:30,공휴일,밤,168,80,66,22
196764,FC223333,FC223333-01,PF427814,2021-10-03,20:00,공휴일,밤,168,80,66,22
196765,FC223333,FC223333-01,PF427814,2021-10-03,20:30,공휴일,밤,168,80,66,22
196766,FC223333,FC223333-01,PF427814,2021-10-03,21:00,공휴일,밤,168,80,66,22

# ETC

In [ ]:
coco = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/coco_clust_final.csv')
coco

,공연시설코드,공연장코드,공연코드,공연횟수,좌석수,사전예매건수,사전취소건수,당일예매건수,당일취소건수,전체예매건수,...,교통개수,무대시설,공연기간,좌석등급개수,평일평균횟수,주말평균횟수,공휴일평균횟수,할인종류개수,할인예매건수,수상실적개수
0,FC222005,FC222005-02,PF374942,4,318.0,27,12,0,0,27,...,28,2,2,2,2.0,2.0,0.0,3,6,0
1,FC222005,FC222005-03,PF351529,154,333.0,879,176,136,0,1015,...,28,2,326,2,1.5,1.5,1.0,7,255,0
2,FC222005,FC222005-03,PF424187,2,333.0,34,7,0,0,34,...,28,2,8,2,0.0,1.0,0.0,0,0,0
3,FC222005,FC222005-04,PF361283,258,334.0,4194,1223,348,18,4542,...,28,2,363,3,1.5,1.5,1.5,11,300,0
4,FC222005,FC222005-04,PF422043,14,334.0,65,25,0,0,65,...,28,2,12,1,1.0,2.0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18731,FC225489,FC225489-01,PF310442,1,128.0,66,4,0,0,66,...,49,1,1,2,0.0,1.0,0.0,0,0,0
18732,FC225489,FC225489-01,PF310552,3,128.0,34,5,10,0,44,...,49,1,29,1,1.0,1.0,0.0,4,28,0
18733,FC225489,FC225489-01,PF316039,2,128.0,12,1,1,0,13,...,49,1,36,1,1.0,0.0,0.0,0,0,0
18734,FC225489,FC225489-01,PF424689,2,128.0,9,4,4,0,13,...,49,1,29,1,1.0,0.0,0.0,2,12,0
18735,FC225541,FC225541-01,PF426902,1,171.0,0,0,167,0,167,...,49,1,1,1,1.0,0.0,0.0,0,0,0

In [ ]:
allco = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO_230816_final.csv')
allco = allco.drop_duplicates(subset=['공연코드'])

In [ ]:
merged_df = pd.merge(coco, allco[['공연코드', '장르명']], on='공연코드',how='inner')
merged_df

,공연시설코드,공연장코드,공연코드,공연횟수,좌석수,사전예매건수,사전취소건수,당일예매건수,당일취소건수,전체예매건수,...,무대시설,공연기간,좌석등급개수,평일평균횟수,주말평균횟수,공휴일평균횟수,할인종류개수,할인예매건수,수상실적개수,장르명
0,FC222005,FC222005-02,PF374942,4,318.0,27,12,0,0,27,...,2,2,2,2.0,2.0,0.0,3,6,0,대중음악
1,FC222005,FC222005-03,PF351529,154,333.0,879,176,136,0,1015,...,2,326,2,1.5,1.5,1.0,7,255,0,뮤지컬
2,FC222005,FC222005-03,PF424187,2,333.0,34,7,0,0,34,...,2,8,2,0.0,1.0,0.0,0,0,0,뮤지컬
3,FC222005,FC222005-04,PF361283,258,334.0,4194,1223,348,18,4542,...,2,363,3,1.5,1.5,1.5,11,300,0,뮤지컬
4,FC222005,FC222005-04,PF422043,14,334.0,65,25,0,0,65,...,2,12,1,1.0,2.0,0.0,0,0,0,연극
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18731,FC225489,FC225489-01,PF310442,1,128.0,66,4,0,0,66,...,1,1,2,0.0,1.0,0.0,0,0,0,복합
18732,FC225489,FC225489-01,PF310552,3,128.0,34,5,10,0,44,...,1,29,1,1.0,1.0,0.0,4,28,0,연극
18733,FC225489,FC225489-01,PF316039,2,128.0,12,1,1,0,13,...,1,36,1,1.0,0.0,0.0,0,0,0,연극
18734,FC225489,FC225489-01,PF424689,2,128.0,9,4,4,0,13,...,1,29,1,1.0,0.0,0.0,2,12,0,연극
18735,FC225541,FC225541-01,PF426902,1,171.0,0,0,167,0,167,...,1,1,1,1.0,0.0,0.0,0,0,0,서양음악(클래식)

In [ ]:
merged_df[merged_df['좌석등급개수'] >= 3]

,공연시설코드,공연장코드,공연코드,공연횟수,좌석수,사전예매건수,사전취소건수,당일예매건수,당일취소건수,전체예매건수,...,무대시설,공연기간,좌석등급개수,평일평균횟수,주말평균횟수,공휴일평균횟수,할인종류개수,할인예매건수,수상실적개수,장르명
3,FC222005,FC222005-04,PF361283,258,334.0,4194,1223,348,18,4542,...,2,363,3,1.5,1.5,1.5,11,300,0,뮤지컬
11,FC222029,FC222029-03,PF310009,2,8473.0,15002,9640,41,0,15043,...,3,2,3,0.0,0.0,1.0,0,0,0,대중음악
13,FC222029,FC222029-03,PF316713,1,8473.0,9527,3984,104,6,9631,...,3,1,3,1.0,0.0,0.0,0,0,0,서양음악(클래식)
14,FC222029,FC222029-03,PF375547,2,8473.0,21102,7337,696,19,21798,...,3,2,5,0.0,1.0,0.0,5,27,0,대중음악
15,FC222029,FC222029-03,PF377902,1,8473.0,3417,1712,0,0,3417,...,3,1,4,1.0,0.0,0.0,0,0,0,대중음악
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18351,FC224855,FC224855-01,PF374983,3,504.0,130,34,362,2,492,...,2,3,3,1.0,1.0,0.0,13,453,0,한국음악(국악)
18363,FC224855,FC224855-01,PF383651,11,504.0,244,37,813,9,1057,...,2,10,3,1.0,1.5,0.0,16,997,0,연극
18380,FC224855,FC224855-01,PF394556,2,504.0,168,36,207,3,375,...,2,2,3,1.0,0.0,0.0,11,302,0,무용(서양/한국무용)
18385,FC224855,FC224855-01,PF396456,14,504.0,1066,228,385,17,1451,...,2,16,3,1.0,1.0,1.0,17,1436,0,연극
18707,FC225267,FC225267-01,PF422511,13,1335.0,26103,10888,218,80,26321,...,2,11,6,1.0,2.0,2.0,11,7031,0,뮤지컬

In [ ]:
merged_df[(merged_df['공연기간'] == 1) & (merged_df['공연횟수'] == 1)]

,공연시설코드,공연장코드,공연코드,공연횟수,좌석수,사전예매건수,사전취소건수,당일예매건수,당일취소건수,전체예매건수,...,무대시설,공연기간,좌석등급개수,평일평균횟수,주말평균횟수,공휴일평균횟수,할인종류개수,할인예매건수,수상실적개수,장르명
13,FC222029,FC222029-03,PF316713,1,8473.0,9527,3984,104,6,9631,...,3,1 days,3,1.0,0.0,0.0,0,0,0,서양음악(클래식)
15,FC222029,FC222029-03,PF377902,1,8473.0,3417,1712,0,0,3417,...,3,1 days,4,1.0,0.0,0.0,0,0,0,대중음악
16,FC222032,FC222032-01,PF305891,1,475.0,208,92,0,0,208,...,1,1 days,3,0.0,1.0,0.0,0,0,0,서양음악(클래식)
19,FC222032,FC222032-01,PF319758,1,475.0,533,167,0,0,533,...,1,1 days,3,0.0,1.0,0.0,0,0,0,서양음악(클래식)
24,FC222032,FC222032-01,PF379161,1,475.0,316,112,0,0,316,...,1,1 days,1,0.0,1.0,0.0,1,2,0,대중음악
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18727,FC225435,FC225435-01,PF424569,1,90.0,55,9,0,0,55,...,0,1 days,1,1.0,0.0,0.0,0,0,0,뮤지컬
18728,FC225463,FC225463-01,PF425872,1,80.0,20,6,0,0,20,...,0,1 days,1,1.0,0.0,0.0,0,0,0,서양음악(클래식)
18730,FC225487,FC225487-01,PF426665,1,1000.0,7,4,0,0,7,...,0,1 days,1,0.0,1.0,0.0,0,0,0,대중음악
18731,FC225489,FC225489-01,PF310442,1,128.0,66,4,0,0,66,...,1,1 days,2,0.0,1.0,0.0,0,0,0,복합
18735,FC225541,FC225541-01,PF426902,1,171.0,0,0,167,0,167,...,1,1 days,1,1.0,0.0,0.0,0,0,0,서양음악(클래식)

# YM

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/2021YM(new).csv')

FC = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/FC/allFC_230815.csv')
unique_codes_list = FC['공연시설코드'].unique().tolist()

filtered_df = df[df['공연시설코드'].isin(unique_codes_list)]
filtered_df = filtered_df.drop_duplicates()

output_file_path = '/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/2021YM.csv' # 변경!!
filtered_df.to_csv(output_file_path, index=False, encoding="utf-8")
#2019 2020 2021

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/2019YM.csv')

FC = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/FC/allFC_230815.csv')
unique_codes_list = FC['공연시설코드'].unique().tolist()

filtered_df = df[df['공연시설코드'].isin(unique_codes_list)]
filtered_df = filtered_df.drop_duplicates()

output_file_path = '/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/f2019YM.csv' # 변경!!
filtered_df.to_csv(output_file_path, index=False, encoding="utf-8")

<ipython-input-4-d86dd908d610>:1: DtypeWarning: Columns (6,12,14,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/2019YM.csv')

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/2020YM.csv')

FC = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/FC/allFC_230815.csv')
unique_codes_list = FC['공연시설코드'].unique().tolist()

filtered_df = df[df['공연시설코드'].isin(unique_codes_list)]
filtered_df = filtered_df.drop_duplicates()

output_file_path = '/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/f2020YM.csv' # 변경!!
filtered_df.to_csv(output_file_path, index=False, encoding="utf-8")

<ipython-input-5-7618993cf1d7>:1: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/2020YM.csv')

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/2022YM(1).csv')

FC = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/FC/allFC_230815.csv')
unique_codes_list = FC['공연시설코드'].unique().tolist()

filtered_df = df[df['공연시설코드'].isin(unique_codes_list)]
filtered_df = filtered_df.drop_duplicates()

output_file_path = '/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/f2022YM(1).csv' # 변경!!
filtered_df.to_csv(output_file_path, index=False, encoding="utf-8")

<ipython-input-6-461d1649d525>:1: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/2022YM(1).csv')

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/2022YM(2).csv')

FC = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/FC/allFC_230815.csv')
unique_codes_list = FC['공연시설코드'].unique().tolist()

filtered_df = df[df['공연시설코드'].isin(unique_codes_list)]
filtered_df = filtered_df.drop_duplicates()

output_file_path = '/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/f2022YM(2).csv' # 변경!!
filtered_df.to_csv(output_file_path, index=False, encoding="utf-8")

<ipython-input-7-3c9bd6b0d06a>:1: DtypeWarning: Columns (6,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/2022YM(2).csv')

In [ ]:
ym = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/2021YM.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14656465 entries, 0 to 14656464
Data columns (total 23 columns):
 #   Column         Dtype
---  ------         -----
 0   전송사업자코드        object
 1   공연시설코드         object
 2   공연장코드          object
 3   공연코드           object
 4   공연회차           int64
 5   공연일시           object
 6   입장권고유번호        object
 7   예매/취소일시        object
 8   예매/취소구분        int64
 9   예매/취소매수        int64
 10  예매/취소금액        int64
 11  예매/취소방식코드      int64
 12  예매/취소방식명(전송처)  object
 13  결제수단코드         int64
 14  결제수단명(전송처)     object
 15  할인금액           int64
 16  할인종류코드         int64
 17  할인종류명(전송처)     object
 18  장당금액           int64
 19  성별             int64
 20  연령             int64
 21  판매종료일시         object
 22  단독판매여부         bool
dtypes: bool(1), int64(11), object(11)
memory usage: 2.4+ GB

# allCO 장당금액 최대,최소,중간값

## YM sale (취소포함)

In [ ]:
import pandas as pd

In [ ]:
# 작업 디렉토리 설정
%cd /content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM

# 파일명 리스트
csv_filenames = ['2019YM.csv', '2020YM.csv', '2021YM.csv','2022YM(1).csv','2022YM(2).csv']  # 필요한 파일명들로 대체

# 읽어올 특정 열의 이름
target_column = ["공연시설코드","공연장코드",'공연코드', '입장권고유번호', '공연일시','예매/취소일시','예매/취소구분', '예매/취소금액', '할인금액', '장당금액','할인종류명(전송처)']

# 읽어온 데이터를 저장할 빈 DataFrame 생성
combined_data1 = pd.DataFrame()

# 각 파일명별로 특정 열 데이터 읽어와 세로 방향으로 이어붙이기
for csv_filename in csv_filenames:
    df = pd.read_csv(csv_filename, usecols=target_column)
    combined_data1 = pd.concat([combined_data1, df], axis=0, ignore_index=True)

reserve = set(combined_data1[combined_data1['예매/취소구분'] == 1]['입장권고유번호'])

# '예매/취소구분'이 2인 행 중에서 '입장권고유번호'가 예매_set에 없는 행을 선택
candrop = combined_data1.drop(combined_data1[(combined_data1['예매/취소구분'] == 2) & (~combined_data1['입장권고유번호'].isin(reserve))].index)

# 데이터를 두 개의 파일로 나누어 저장
split_idx = len(candrop) // 2
candrop_part1 = candrop.iloc[:split_idx, :]
candrop_part2 = candrop.iloc[split_idx:, :]

candrop_part1.to_csv('/content/drive/MyDrive/KOPIS DATA/Colab/주나/ym_y1.csv', index=False)
candrop_part2.to_csv('/content/drive/MyDrive/KOPIS DATA/Colab/주나/ym_y2.csv', index=False)

/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM

<ipython-input-5-9cd340bfb461>:15: DtypeWarning: Columns (6,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_filename, usecols=target_column)
<ipython-input-5-9cd340bfb461>:15: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_filename, usecols=target_column)
<ipython-input-5-9cd340bfb461>:15: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_filename, usecols=target_column)
<ipython-input-5-9cd340bfb461>:15: DtypeWarning: Columns (6,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_filename, usecols=target_column)

In [ ]:
candrop_part1 = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Colab/주나/ym_y1.csv')
candrop_part1.shape[0]

<ipython-input-3-e5357e5e9519>:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  candrop_part1 = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Colab/주나/ym_y1.csv')

32318915

In [ ]:
candrop_part2 = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Colab/주나/ym_y2.csv')
candrop_part2.shape[0]

32318915

In [ ]:
# 취소도 합친거
%cd /content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM

# 파일명 리스트
csv_filenames = ['2019YM.csv', '2020YM.csv', '2021YM.csv','2022YM(1).csv','2022YM(2).csv']  # 필요한 파일명들로 대체

# 읽어올 특정 열의 이름
target_column = ['공연코드', '입장권고유번호', '공연일시','예매/취소구분', '예매/취소금액', '할인금액', '장당금액']

# 읽어온 데이터를 저장할 빈 DataFrame 생성
combined_data1 = pd.DataFrame()

# 각 파일명별로 특정 열 데이터 읽어와 세로 방향으로 이어붙이기
for csv_filename in csv_filenames:
    df = pd.read_csv(csv_filename, usecols=target_column)
    combined_data1 = pd.concat([combined_data1, df], axis=0, ignore_index=True)

reserve = set(combined_data1[combined_data1['예매/취소구분'] == 1]['입장권고유번호'])

# '예매/취소구분'이 2인 행 중에서 '입장권고유번호'가 예매_set에 없는 행을 선택
cancel = combined_data1.drop(combined_data1[(combined_data1['예매/취소구분'] == 2) & (~combined_data1['입장권고유번호'].isin(reserve))].index)
cancel.to_csv('/content/drive/MyDrive/KOPIS DATA/Colab/주나/ym_sale_all.csv', index=False)

/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM

<ipython-input-2-2a906ba3d985>:15: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_filename, usecols=target_column)
<ipython-input-2-2a906ba3d985>:15: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_filename, usecols=target_column)

In [ ]:
sale = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/ym_sale_all.csv')
sale

,공연코드,공연일시,입장권고유번호,예매/취소구분,예매/취소금액,할인금액,장당금액
0,PF373404,2019-07-09 15:00,PTD5061906191646470,1,0,0,0
1,PF373404,2019-07-09 15:00,PTD3901906222312030,1,0,0,0
2,PF373404,2019-07-09 15:00,PTD5061906191646470,2,0,0,0
3,PF373404,2019-07-09 19:00,PTD2531906102003380,1,0,0,0
4,PF373404,2019-07-09 19:00,PTD4411906102218020,1,0,0,0
...,...,...,...,...,...,...,...
64637825,PF426714,2022-12-31 23:30,39539092431600024,1,88000,0,88000
64637826,PF426714,2022-12-31 23:30,39539092431600024,2,88000,0,88000
64637827,PF426714,2022-12-31 23:30,39539092822300035,1,88000,0,88000
64637828,PF426714,2022-12-31 23:30,39539093471400046,1,88000,0,88000
64637829,PF426714,2022-12-31 23:30,39539093721600024,1,88000,0,88000

In [ ]:
sale[(sale['공연코드'] == 'PF300001') & (sale['공연일시'] == '2022-04-28 20:00')]

,공연코드,공연일시,입장권고유번호,예매/취소구분,예매/취소금액,할인금액,장당금액
44587855,PF300001,2022-04-28 20:00,T1908589580,1,35750,0,35750
44587856,PF300001,2022-04-28 20:00,T1908590070,1,35750,0,35750
44587857,PF300001,2022-04-28 20:00,T1908590130,1,35750,0,35750
44587858,PF300001,2022-04-28 20:00,T1908590780,1,35750,0,35750
44587859,PF300001,2022-04-28 20:00,T1908591070,1,35750,0,35750
...,...,...,...,...,...,...,...
44588130,PF300001,2022-04-28 20:00,T1910990170,2,35750,0,35750
44588131,PF300001,2022-04-28 20:00,T1911372130,2,35750,0,35750
44588132,PF300001,2022-04-28 20:00,T1912463120,2,35750,0,35750
44588133,PF300001,2022-04-28 20:00,T1912467640,2,30800,0,30800
44588134,PF300001,2022-04-28 20:00,T1912804920,2,35750,0,35750

In [ ]:
sale = sale.drop(columns=['입장권고유번호','예매/취소구분'])
sale['티켓값'] = sale['예매/취소금액'] + sale['할인금액']
sale = sale.drop_duplicates()
sale

              공연코드              공연일시  예매/취소금액  할인금액   장당금액    티켓값
0         PF373404  2019-07-09 15:00        0     0      0      0
3         PF373404  2019-07-09 19:00        0     0      0      0
10        PF373403  2019-07-09 20:00        0     0      0      0
17        PF361234  2019-07-02 15:00    18000     0      0  18000
19        PF361234  2019-07-02 19:30    18000     0      0  18000
...            ...               ...      ...   ...    ...    ...
64636115  PF425243  2022-12-31 22:20    66000     0  66000  66000
64636209  PF425243  2022-12-31 22:20        0     0      0      0
64636332  PF425243  2022-12-31 22:20    19800     0  19800  19800
64636338  PF425243  2022-12-31 22:20    16500     0  16500  16500
64636820  PF426714  2022-12-31 23:30    88000     0  88000  88000

[1423631 rows x 6 columns]

In [ ]:
grouped = sale.groupby('공연일시')['티켓값'].agg(['max', 'min', 'median']).reset_index()

# 원본 데이터프레임과 합치기
result_df = pd.merge(sale, grouped, on='공연일시', suffixes=('', '_공연일시'))
result_df = result_df[['공연코드','공연일시','max','min','median']]
result_df = result_df.drop_duplicates()
result_df

             공연코드              공연일시     max    min   median
0        PF373404  2019-07-09 15:00   13000      0   9000.0
1        PF356804  2019-07-09 15:00   13000      0   9000.0
5        PF352845  2019-07-09 15:00   13000      0   9000.0
7        PF373404  2019-07-09 19:00  140000      0  90000.0
8        PF369385  2019-07-09 19:00  140000      0  90000.0
...           ...               ...     ...    ...      ...
1423593  PF423813  2022-12-31 21:50   45000      0  19950.0
1423599  PF424726  2022-12-31 22:00  100000      0  49000.0
1423616  PF424996  2022-12-31 22:00  100000      0  49000.0
1423619  PF425243  2022-12-31 22:20   66000      0  38500.0
1423630  PF426714  2022-12-31 23:30   88000  88000  88000.0

[196719 rows x 5 columns]

In [ ]:
result_df.rename(columns={'max': '티켓최고가', 'min': '티켓최저가','median': '티켓중간값'}, inplace=True)
result_df.to_csv('/content/drive/MyDrive/KOPIS DATA/Colab/주나/ym_ticket_cost.csv', index=False)

## 장당금액+좌석등급수+공연기간+코로나확진자

In [ ]:
allCO = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO_230816_sale_update.csv')
allCO = allCO[["공연코드",	"공연일시", "공연기간", "좌석등급개수"]]

<ipython-input-30-04da42b667a9>:1: DtypeWarning: Columns (14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  allCO = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO_230816_sale_update.csv')

In [ ]:
fc = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO_230816_sale_update.csv',usecols=["공연시설코드",'공연장코드','공연코드','공연일시'])
fc

          공연시설코드        공연장코드      공연코드                 공연일시
0       FC222055  FC222055-02  PF300001  2022-04-26 20:00:00
1       FC222055  FC222055-02  PF300001  2022-04-27 20:00:00
2       FC222055  FC222055-02  PF300001  2022-04-28 20:00:00
3       FC222055  FC222055-02  PF300001  2022-04-29 20:00:00
4       FC222055  FC222055-02  PF300001  2022-04-30 15:00:00
...          ...          ...       ...                  ...
196762  FC223333  FC223333-01  PF427814  2021-10-03 19:00:00
196763  FC223333  FC223333-01  PF427814  2021-10-03 19:30:00
196764  FC223333  FC223333-01  PF427814  2021-10-03 20:00:00
196765  FC223333  FC223333-01  PF427814  2021-10-03 20:30:00
196766  FC223333  FC223333-01  PF427814  2021-10-03 21:00:00

[196767 rows x 4 columns]

In [ ]:
allCO

            공연코드                 공연일시  공연기간  좌석등급개수
0       PF300001  2022-04-26 20:00:00    66       2
1       PF300001  2022-04-27 20:00:00    66       2
2       PF300001  2022-04-28 20:00:00    66       2
3       PF300001  2022-04-29 20:00:00    66       2
4       PF300001  2022-04-30 15:00:00    66       2
...          ...                  ...   ...     ...
196762  PF427814  2021-10-03 19:00:00    10       1
196763  PF427814  2021-10-03 19:30:00    10       1
196764  PF427814  2021-10-03 20:00:00    10       1
196765  PF427814  2021-10-03 20:30:00    10       1
196766  PF427814  2021-10-03 21:00:00    10       1

[196767 rows x 4 columns]

In [ ]:
covid = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/Outsource/seoul_covid.csv',usecols=["공연일","총확진자"])

In [ ]:
covid

             공연일     총확진자
0     2020-02-05        8
1     2020-02-06       11
2     2020-02-07       10
3     2020-02-08       10
4     2020-02-09       10
...          ...      ...
1056  2022-12-27  5610852
1057  2022-12-28  5626635
1058  2022-12-29  5640031
1059  2022-12-30  5651699
1060  2022-12-31  5663251

[1061 rows x 2 columns]

In [ ]:
from datetime import datetime
allCO['공연일시'] = allCO['공연일시'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S').strftime('%Y-%m-%d %H:%M'))

co_ticket = pd.merge(allCO,result_df,on=['공연코드','공연일시'])
co_ticket

In [ ]:
co_ticket['공연일시'] = pd.to_datetime(co_ticket['공연일시'])
co_ticket['공연일'] = co_ticket['공연일시'].dt.date
co_ticket

,공연코드,공연일시,공연기간,좌석등급개수,티켓최고가,티켓최저가,티켓중간값,공연일
0,PF300001,2022-04-26 20:00:00,66,2,88000,0,35200.0,2022-04-26
1,PF300001,2022-04-27 20:00:00,66,2,88000,0,35200.0,2022-04-27
2,PF300001,2022-04-28 20:00:00,66,2,100000,0,35000.0,2022-04-28
3,PF300001,2022-04-29 20:00:00,66,2,143000,0,35200.0,2022-04-29
4,PF300001,2022-04-30 15:00:00,66,2,100000,0,33000.0,2022-04-30
...,...,...,...,...,...,...,...,...
196714,PF427814,2021-10-03 19:00:00,10,1,158000,0,80750.0,2021-10-03
196715,PF427814,2021-10-03 19:30:00,10,1,30000,0,18000.0,2021-10-03
196716,PF427814,2021-10-03 20:00:00,10,1,30000,0,19900.0,2021-10-03
196717,PF427814,2021-10-03 20:30:00,10,1,30000,30000,30000.0,2021-10-03
196718,PF427814,2021-10-03 21:00:00,10,1,30000,30000,30000.0,2021-10-03

In [ ]:
covid['공연일'] = pd.to_datetime(covid['공연일'])
co_ticket['공연일'] = pd.to_datetime(co_ticket['공연일'])

In [ ]:
merged_df = pd.merge(co_ticket, covid, on=['공연일'], how='left')
merged_df['총확진자'] = merged_df['총확진자'].fillna(0)
merged_df = merged_df.drop(['공연일'], axis=1)

# Timestamp 객체를 문자열로 변환 후 datetime 포맷으로 변경
merged_df['공연일시'] = merged_df['공연일시'].apply(lambda x: datetime.strptime(str(x), '%Y-%m-%d %H:%M:%S').strftime('%Y-%m-%d %H:%M'))

In [ ]:
merged_df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/coco_ticket_price(196719).csv', index=False)

In [ ]:
merged_df

,공연코드,공연일시,공연기간,좌석등급개수,티켓최고가,티켓최저가,티켓중간값,총확진자
0,PF300001,2022-04-26 20:00,66,2,88000,0,35200.0,3446789.0
1,PF300001,2022-04-27 20:00,66,2,88000,0,35200.0,3458306.0
2,PF300001,2022-04-28 20:00,66,2,100000,0,35000.0,3467402.0
3,PF300001,2022-04-29 20:00,66,2,143000,0,35200.0,3475126.0
4,PF300001,2022-04-30 15:00,66,2,100000,0,33000.0,3481581.0
...,...,...,...,...,...,...,...,...
196714,PF427814,2021-10-03 19:00,10,1,158000,0,80750.0,102939.0
196715,PF427814,2021-10-03 19:30,10,1,30000,0,18000.0,102939.0
196716,PF427814,2021-10-03 20:00,10,1,30000,0,19900.0,102939.0
196717,PF427814,2021-10-03 20:30,10,1,30000,30000,30000.0,102939.0
196718,PF427814,2021-10-03 21:00,10,1,30000,30000,30000.0,102939.0

In [ ]:
merged_df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/coco_clust_disc_prize_196719.csv')

## +공연시설코드,공연장코드

In [ ]:
fc

          공연시설코드        공연장코드      공연코드                 공연일시
0       FC222055  FC222055-02  PF300001  2022-04-26 20:00:00
1       FC222055  FC222055-02  PF300001  2022-04-27 20:00:00
2       FC222055  FC222055-02  PF300001  2022-04-28 20:00:00
3       FC222055  FC222055-02  PF300001  2022-04-29 20:00:00
4       FC222055  FC222055-02  PF300001  2022-04-30 15:00:00
...          ...          ...       ...                  ...
196762  FC223333  FC223333-01  PF427814  2021-10-03 19:00:00
196763  FC223333  FC223333-01  PF427814  2021-10-03 19:30:00
196764  FC223333  FC223333-01  PF427814  2021-10-03 20:00:00
196765  FC223333  FC223333-01  PF427814  2021-10-03 20:30:00
196766  FC223333  FC223333-01  PF427814  2021-10-03 21:00:00

[196767 rows x 4 columns]

In [ ]:
fc['공연일시'] = pd.to_datetime(fc['공연일시'])
merged_df['공연일시'] = pd.to_datetime(merged_df['공연일시'])
df = pd.merge(fc,merged_df, on=['공연코드','공연일시'], how='inner')
df

,공연시설코드,공연장코드,공연코드,공연일시,공연기간,좌석등급개수,티켓최고가,티켓최저가,티켓중간값,총확진자,할인종류개수,할인예매건수,수상실적개수
0,FC222055,FC222055-02,PF300001,2022-04-26 20:00:00,66,2,88000,0,35200,3446789,0,0,0
1,FC222055,FC222055-02,PF300001,2022-04-27 20:00:00,66,2,88000,0,35200,3458306,0,0,0
2,FC222055,FC222055-02,PF300001,2022-04-28 20:00:00,66,2,100000,0,35000,3467402,0,0,0
3,FC222055,FC222055-02,PF300001,2022-04-29 20:00:00,66,2,143000,0,35200,3475126,0,0,0
4,FC222055,FC222055-02,PF300001,2022-04-30 15:00:00,66,2,100000,0,33000,3481581,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
196714,FC223333,FC223333-01,PF427814,2021-10-03 19:00:00,10,1,158000,0,80750,102939,1,1,0
196715,FC223333,FC223333-01,PF427814,2021-10-03 19:30:00,10,1,30000,0,18000,102939,1,2,0
196716,FC223333,FC223333-01,PF427814,2021-10-03 20:00:00,10,1,30000,0,19900,102939,3,6,0
196717,FC223333,FC223333-01,PF427814,2021-10-03 20:30:00,10,1,30000,30000,30000,102939,1,1,0
196718,FC223333,FC223333-01,PF427814,2021-10-03 21:00:00,10,1,30000,30000,30000,102939,1,1,0

In [ ]:
from datetime import datetime
# Timestamp 객체를 문자열로 변환 후 datetime 포맷으로 변경
df['공연일시'] = df['공연일시'].apply(lambda x: datetime.strptime(str(x), '%Y-%m-%d %H:%M:%S').strftime('%Y-%m-%d %H:%M'))
df.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/coco_clust_196719.csv', index=False)

In [ ]:
df

,공연시설코드,공연장코드,공연코드,공연일시,공연기간,좌석등급개수,티켓최고가,티켓최저가,티켓중간값,총확진자,할인종류개수,할인예매건수,수상실적개수
0,FC222055,FC222055-02,PF300001,2022-04-26 20:00,66,2,88000,0,35200,3446789,0,0,0
1,FC222055,FC222055-02,PF300001,2022-04-27 20:00,66,2,88000,0,35200,3458306,0,0,0
2,FC222055,FC222055-02,PF300001,2022-04-28 20:00,66,2,100000,0,35000,3467402,0,0,0
3,FC222055,FC222055-02,PF300001,2022-04-29 20:00,66,2,143000,0,35200,3475126,0,0,0
4,FC222055,FC222055-02,PF300001,2022-04-30 15:00,66,2,100000,0,33000,3481581,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
196714,FC223333,FC223333-01,PF427814,2021-10-03 19:00,10,1,158000,0,80750,102939,1,1,0
196715,FC223333,FC223333-01,PF427814,2021-10-03 19:30,10,1,30000,0,18000,102939,1,2,0
196716,FC223333,FC223333-01,PF427814,2021-10-03 20:00,10,1,30000,0,19900,102939,3,6,0
196717,FC223333,FC223333-01,PF427814,2021-10-03 20:30,10,1,30000,30000,30000,102939,1,1,0
196718,FC223333,FC223333-01,PF427814,2021-10-03 21:00,10,1,30000,30000,30000,102939,1,1,0

## +교통개수

In [ ]:
import pandas as pd

In [ ]:
code = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO_230816_sale_update.csv')
code

<ipython-input-3-df15139154a5>:1: DtypeWarning: Columns (14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  code = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/allCO_230816_sale_update.csv')

,행정동코드,공연시설코드,공연장코드,공연코드,공연일시,공연일,공연시간,공연시작일자,공연종료일자,소요시간,...,공연기간,휴일,시간대,좌석등급개수,확진자변화율,강수,기온,습도,미세먼지등급,초미세먼지등급
0,1101064,FC222055,FC222055-02,PF300001,2022-04-26 20:00:00,2022-04-26,20:00,2022-04-26,2022-06-30,105.0,...,66,평일,밤,2,184.694520,0.0,13.200000,31.0,1.0,1.0
1,1101064,FC222055,FC222055-02,PF300001,2022-04-27 20:00:00,2022-04-27,20:00,2022-04-26,2022-06-30,105.0,...,66,평일,밤,2,-15.066372,0.0,11.700000,54.0,2.0,1.0
2,1101064,FC222055,FC222055-02,PF300001,2022-04-28 20:00:00,2022-04-28,20:00,2022-04-26,2022-06-30,105.0,...,66,평일,밤,2,-20.908223,2.5,10.800000,95.0,1.0,1.0
3,1101064,FC222055,FC222055-02,PF300001,2022-04-29 20:00:00,2022-04-29,20:00,2022-04-26,2022-06-30,105.0,...,66,평일,밤,2,-15.182786,0.0,11.000000,70.0,0.0,0.0
4,1101064,FC222055,FC222055-02,PF300001,2022-04-30 15:00:00,2022-04-30,15:00,2022-04-26,2022-06-30,105.0,...,66,주말,낮,2,-16.450945,0.0,10.100000,65.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196762,1103071,FC223333,FC223333-01,PF427814,2021-10-03 19:00:00,2021-10-03,19:00,2021-09-24,2021-10-03,NaN,...,10,공휴일,밤,1,-7.187894,0.0,21.000000,70.0,1.0,1.0
196763,1103071,FC223333,FC223333-01,PF427814,2021-10-03 19:30:00,2021-10-03,19:30,2021-09-24,2021-10-03,NaN,...,10,공휴일,밤,1,-7.187894,0.0,21.000000,70.0,1.0,1.0
196764,1103071,FC223333,FC223333-01,PF427814,2021-10-03 20:00:00,2021-10-03,20:00,2021-09-24,2021-10-03,NaN,...,10,공휴일,밤,1,-7.187894,0.0,21.299999,67.0,1.0,1.0
196765,1103071,FC223333,FC223333-01,PF427814,2021-10-03 20:30:00,2021-10-03,20:30,2021-09-24,2021-10-03,NaN,...,10,공휴일,밤,1,-7.187894,0.0,21.299999,67.0,1.0,1.0
196766,1103071,FC223333,FC223333-01,PF427814,2021-10-03 21:00:00,2021-10-03,21:00,2021-09-24,2021-10-03,NaN,...,10,공휴일,밤,1,-7.187894,0.0,21.500000,68.0,1.0,1.0

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/coco_clust_196719.csv')
df

,공연시설코드,공연장코드,공연코드,공연일시,공연기간,좌석등급개수,티켓최고가,티켓최저가,티켓중간값,총확진자,할인종류개수,할인예매건수,수상실적개수,총티켓예매수,평균할인율,평균사전예매율,평균당일예매율
0,FC222055,FC222055-02,PF300001,2022-04-26 20:00:00,66,2,88000,0,35200,3446789,0,0,0,247.0,0.000000,0.919028,0.080972
1,FC222055,FC222055-02,PF300001,2022-04-27 20:00:00,66,2,88000,0,35200,3458306,0,0,0,205.0,0.000000,0.926829,0.073171
2,FC222055,FC222055-02,PF300001,2022-04-28 20:00:00,66,2,100000,0,35000,3467402,0,0,0,140.0,0.000000,1.000000,0.000000
3,FC222055,FC222055-02,PF300001,2022-04-29 20:00:00,66,2,143000,0,35200,3475126,0,0,0,225.0,0.000000,0.960000,0.040000
4,FC222055,FC222055-02,PF300001,2022-04-30 15:00:00,66,2,100000,0,33000,3481581,0,0,0,243.0,0.000000,0.991770,0.008230
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196714,FC223333,FC223333-01,PF427814,2021-10-03 19:00:00,10,1,158000,0,80750,102939,1,1,0,1.0,0.400000,1.000000,0.000000
196715,FC223333,FC223333-01,PF427814,2021-10-03 19:30:00,10,1,30000,0,18000,102939,1,2,0,2.0,0.500000,1.000000,0.000000
196716,FC223333,FC223333-01,PF427814,2021-10-03 20:00:00,10,1,30000,0,19900,102939,3,6,0,6.0,0.333333,1.000000,0.000000
196717,FC223333,FC223333-01,PF427814,2021-10-03 20:30:00,10,1,30000,30000,30000,102939,1,1,0,1.0,0.400000,1.000000,0.000000
196718,FC223333,FC223333-01,PF427814,2021-10-03 21:00:00,10,1,30000,30000,30000,102939,1,1,0,1.0,0.500000,1.000000,0.000000

In [ ]:
trans = pd.read_csv("/content/drive/MyDrive/KOPIS DATA/Data/csv/all/FC/allFC_741_code.csv",usecols=['공연시설코드','행정동코드','버스정류장_개수','지하철역_개수'])
trans

       공연시설코드  버스정류장_개수  지하철역_개수    행정동코드
0    FC222055        19        1  1101064
1    FC223051        49        0  1118057
2    FC223420        31        0  1101064
3    FC222905        36        0  1117056
4    FC222789        28        0  1109062
..        ...       ...      ...      ...
736  FC225484        35        0  1122066
737  FC225487         8        0  1122058
738  FC223928        44        0  1113075
739  FC225541        24        1  1109075
740  FC225413        30        1  1123079

[741 rows x 4 columns]

In [ ]:
trans['교통개수'] = trans['지하철역_개수'] + trans['버스정류장_개수']
trans = trans.drop(columns=['지하철역_개수','버스정류장_개수'])
trans

       공연시설코드    행정동코드  교통개수
0    FC222055  1101064    20
1    FC223051  1118057    49
2    FC223420  1101064    31
3    FC222905  1117056    36
4    FC222789  1109062    28
..        ...      ...   ...
736  FC225484  1122066    35
737  FC225487  1122058     8
738  FC223928  1113075    44
739  FC225541  1109075    25
740  FC225413  1123079    31

[741 rows x 3 columns]

In [ ]:
transf = pd.merge(df,trans, on=['공연시설코드'], how='inner')
transf

,공연시설코드,공연장코드,공연코드,공연일시,공연기간,좌석등급개수,티켓최고가,티켓최저가,티켓중간값,총확진자,할인종류개수,할인예매건수,수상실적개수,총티켓예매수,평균할인율,평균사전예매율,평균당일예매율,행정동코드,교통개수
0,FC222055,FC222055-02,PF300001,2022-04-26 20:00:00,66,2,88000,0,35200,3446789,0,0,0,247.0,0.0,0.919028,0.080972,1101064,20
1,FC222055,FC222055-02,PF300001,2022-04-27 20:00:00,66,2,88000,0,35200,3458306,0,0,0,205.0,0.0,0.926829,0.073171,1101064,20
2,FC222055,FC222055-02,PF300001,2022-04-28 20:00:00,66,2,100000,0,35000,3467402,0,0,0,140.0,0.0,1.000000,0.000000,1101064,20
3,FC222055,FC222055-02,PF300001,2022-04-29 20:00:00,66,2,143000,0,35200,3475126,0,0,0,225.0,0.0,0.960000,0.040000,1101064,20
4,FC222055,FC222055-02,PF300001,2022-04-30 15:00:00,66,2,100000,0,33000,3481581,0,0,0,243.0,0.0,0.991770,0.008230,1101064,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196714,FC225484,FC225484-01,PF426502,2022-12-31 18:00:00,1,1,300000,0,39300,5663251,0,0,0,12.0,0.0,1.000000,0.000000,1122066,35
196715,FC225487,FC225487-01,PF426665,2022-12-31 21:00:00,1,1,100000,13500,37500,5663251,0,0,0,7.0,0.0,1.000000,0.000000,1122058,8
196716,FC225541,FC225541-01,PF426902,2022-12-23 19:00:00,1,1,300000,0,35000,5566002,0,0,0,167.0,0.0,0.000000,1.000000,1109075,25
196717,FC225413,FC225413-01,PF427510,2021-06-05 18:00:00,1,1,120000,0,39600,45020,0,0,0,135.0,0.0,1.000000,0.000000,1123079,31
196718,FC225413,FC225413-01,PF427511,2021-05-14 20:00:00,1,1,88000,0,39600,40576,0,0,0,149.0,0.0,1.000000,0.000000,1123079,31

In [ ]:
transf.to_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/CO/coco_clust_196719.csv', index=False)

In [ ]:
ym = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/2022YM_surv.csv')

In [ ]:
FC = pd.read_csv('/content/drive/MyDrive/KOPIS DATA/Data/csv/all/FC/allFC_230815.csv')
unique_codes_list = FC['공연시설코드'].unique().tolist()

filtered_df = ym[ym['공연시설코드'].isin(unique_codes_list)]
filtered_df = filtered_df.drop_duplicates()

filtered_df

,공연시설코드,공연장코드,공연코드,공연일시,입장권고유번호,예매/취소일시,예매/취소구분,판매시작일시,판매종료일시,판매기간
0,FC222028,FC222028-01,PF343804,2022-04-18 17:15:00,W2229628466001,2022-04-18 16:28:00,1,2022-04-18 00:00:00,2022-04-18 17:15:00,1
1,FC222028,FC222028-01,PF343804,2022-04-18 17:15:00,W2229628466002,2022-04-18 16:28:00,1,2022-04-18 00:00:00,2022-04-18 17:15:00,1
2,FC222028,FC222028-01,PF343804,2022-04-19 15:00:00,W2229226914001,2022-04-19 00:33:00,1,2022-04-18 00:00:00,2022-04-19 15:00:00,2
3,FC222028,FC222028-01,PF343804,2022-04-19 15:00:00,W2229226914002,2022-04-19 00:33:00,1,2022-04-18 00:00:00,2022-04-19 15:00:00,2
4,FC223396,FC223396-01,PF307406,2022-04-19 17:00:00,W2250065445001,2022-04-19 15:18:00,1,2022-04-18 00:00:00,2022-04-19 16:55:00,2
...,...,...,...,...,...,...,...,...,...,...
22654967,FC224161,FC224161-01,PF426714,2022-12-31 23:30:00,39539092431600024,2022-12-30 16:30:00,1,2022-12-20 19:00:00,2022-12-30 17:00:00,10
22654968,FC224161,FC224161-01,PF426714,2022-12-31 23:30:00,39539092431600024,2022-12-30 16:41:00,2,2022-12-20 19:00:00,2022-12-30 17:00:00,10
22654969,FC224161,FC224161-01,PF426714,2022-12-31 23:30:00,39539092822300035,2022-12-30 16:34:00,1,2022-12-20 19:00:00,2022-12-30 17:00:00,10
22654970,FC224161,FC224161-01,PF426714,2022-12-31 23:30:00,39539093471400046,2022-12-30 16:40:00,1,2022-12-20 19:00:00,2022-12-30 17:00:00,10
22654971,FC224161,FC224161-01,PF426714,2022-12-31 23:30:00,39539093721600024,2022-12-30 16:41:00,1,2022-12-20 19:00:00,2022-12-30 17:00:00,10

In [ ]:
output_file_path = '/content/drive/MyDrive/KOPIS DATA/Data/csv/all/YM/2022YM_surv.csv'
filtered_df.to_csv(output_file_path, index=False, encoding="utf-8")